"use client";

/**
 * Auto Article Panel — SUPER_ADMIN only
 * - Master toggle (auto_article_enabled SystemSetting)
 * - List auto-generated articles (filter client-side by isAutoGenerated=true)
 * - Placeholder: TargetKeyword management (endpoint /api/target-keywords not yet available)
 */

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { redirect } from "next/navigation";
import {
  Bot,
  Sparkles,
  FileText,
  Edit,
  Trash2,
  Loader2,
  AlertCircle,
  Info,
  RefreshCw,
  Terminal,
} from "lucide-react";
import { useToast } from "@/components/ui/Toast";
import { useConfirm } from "@/components/ui/ConfirmDialog";

interface Article {
  id: string;
  title: string;
  slug: string;
  status: string;
  isAutoGenerated?: boolean;
  createdAt: string;
  publishedAt: string | null;
}

const statusColors: Record<string, string> = {
  PUBLISHED: "bg-primary-light text-primary",
  IN_REVIEW: "bg-yellow-50 text-yellow-600",
  DRAFT: "bg-surface-tertiary text-txt-secondary",
  REJECTED: "bg-red-50 text-red-600",
  APPROVED: "bg-blue-50 text-blue-600",
  ARCHIVED: "bg-surface-tertiary text-txt-muted",
};

const statusLabels: Record<string, string> = {
  PUBLISHED: "Dipublikasi",
  IN_REVIEW: "Menunggu Review",
  DRAFT: "Draf",
  REJECTED: "Ditolak",
  APPROVED: "Disetujui",
  ARCHIVED: "Diarsipkan",
};

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("id-ID", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function AutoArtikelPage() {
  const { data: session, status: sessionStatus } = useSession();
  const userRole = session?.user?.role || "";
  const { success: showSuccess, error: showError } = useToast();
  const { confirm } = useConfirm();

  const [enabled, setEnabled] = useState<boolean>(false);
  const [loadingSettings, setLoadingSettings] = useState<boolean>(true);
  const [savingToggle, setSavingToggle] = useState<boolean>(false);
  const [articles, setArticles] = useState<Article[]>([]);
  const [loadingArticles, setLoadingArticles] = useState<boolean>(true);

  if (sessionStatus !== "loading" && session && userRole !== "SUPER_ADMIN") {
    redirect("/panel/dashboard");
  }

  const fetchSettings = useCallback(async () => {
    try {
      setLoadingSettings(true);
      const res = await fetch("/api/settings");
      if (res.ok) {
        const json = await res.json();
        setEnabled(String(json.data?.auto_article_enabled ?? "false") === "true");
      }
    } catch {
      /* non-critical */
    } finally {
      setLoadingSettings(false);
    }
  }, []);

  const fetchArticles = useCallback(async () => {
    try {
      setLoadingArticles(true);
      const res = await fetch("/api/articles?status=ALL&limit=500");
      if (res.ok) {
        const json = await res.json();
        const all = (json.data?.articles || []) as Article[];
        setArticles(all.filter((a) => a.isAutoGenerated));
      }
    } catch {
      /* non-critical */
    } finally {
      setLoadingArticles(false);
    }
  }, []);

  useEffect(() => {
    fetchSettings();
    fetchArticles();
  }, [fetchSettings, fetchArticles]);

  async function handleToggle() {
    try {
      setSavingToggle(true);
      const newValue = !enabled;
      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          key: "auto_article_enabled",
          value: newValue ? "true" : "false",
        }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menyimpan");
      setEnabled(newValue);
      showSuccess(
        newValue ? "Auto Artikel diaktifkan." : "Auto Artikel dinonaktifkan.",
      );
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menyimpan");
    } finally {
      setSavingToggle(false);
    }
  }

  async function handleDelete(id: string) {
    const ok = await confirm({
      title: "Hapus draf",
      message: "Yakin ingin menghapus draf auto-generated ini?",
      variant: "danger",
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/articles/${id}`, { method: "DELETE" });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menghapus");
      showSuccess("Draf berhasil dihapus.");
      fetchArticles();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menghapus");
    }
  }

  const stats = {
    total: articles.length,
    draft: articles.filter((a) => a.status === "DRAFT").length,
    review: articles.filter((a) => a.status === "IN_REVIEW").length,
    published: articles.filter((a) => a.status === "PUBLISHED").length,
  };

  if (sessionStatus === "loading") {
    return (
      <div className="flex min-h-[40vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
      </div>
    );
  }

  return (
    <div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <Bot size={24} className="text-primary" />
            <h1 className="text-xl sm:text-3xl font-bold text-txt-primary">
              Auto Artikel
            </h1>
          </div>
          <p className="mt-1 text-sm text-txt-secondary">
            Generator artikel otomatis via AI berdasarkan Target Keyword.
          </p>
        </div>
        <button
          onClick={() => {
            fetchSettings();
            fetchArticles();
          }}
          className="btn-ghost flex items-center gap-2 px-3 py-2.5 text-sm"
        >
          <RefreshCw size={14} /> Refresh
        </button>
      </div>

      {/* Master Toggle */}
      <div className="mb-6 rounded-2xl border border-border bg-surface p-5 shadow-card">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-light">
              <Sparkles size={18} className="text-primary" />
            </div>
            <div>
              <h2 className="text-base font-bold text-txt-primary">
                Auto Generation
              </h2>
              <p className="text-xs text-txt-secondary">
                {enabled
                  ? "Cron akan men-generate artikel otomatis setiap jam."
                  : "Nonaktif — cron di-skip meskipun dipicu."}
              </p>
            </div>
          </div>
          <button
            onClick={handleToggle}
            disabled={loadingSettings || savingToggle}
            className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors disabled:opacity-50 ${
              enabled ? "bg-primary" : "bg-surface-tertiary"
            }`}
            aria-label="Toggle auto-article"
          >
            <span
              className={`inline-block h-5 w-5 transform rounded-full bg-white shadow transition-transform ${
                enabled ? "translate-x-6" : "translate-x-1"
              }`}
            />
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Total Auto</p>
          <p className="mt-1 text-2xl font-extrabold text-txt-primary">
            {stats.total}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Draf</p>
          <p className="mt-1 text-2xl font-extrabold text-txt-secondary">
            {stats.draft}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Review</p>
          <p className="mt-1 text-2xl font-extrabold text-yellow-600">
            {stats.review}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Dipublikasi</p>
          <p className="mt-1 text-2xl font-extrabold text-primary">
            {stats.published}
          </p>
        </div>
      </div>

      {/* Target Keywords Placeholder */}
      <div className="mb-6 rounded-2xl border border-yellow-200 bg-yellow-50 p-5">
        <div className="flex items-start gap-3">
          <AlertCircle size={18} className="mt-0.5 text-yellow-600 shrink-0" />
          <div>
            <h3 className="text-sm font-bold text-yellow-800">
              Target Keyword Manager
            </h3>
            <p className="mt-1 text-xs text-yellow-700">
              UI manajemen Target Keyword belum tersedia. Endpoint{" "}
              <code className="font-mono bg-yellow-100 px-1 py-0.5 rounded">
                /api/target-keywords
              </code>{" "}
              perlu dibuat dulu. Sementara, keyword bisa ditambahkan langsung
              via Prisma Studio (<code className="font-mono">TargetKeyword</code>
              ).
            </p>
          </div>
        </div>
      </div>

      {/* Trigger Info */}
      <div className="mb-6 rounded-2xl border border-blue-200 bg-blue-50 p-5">
        <div className="flex items-start gap-3">
          <Terminal size={18} className="mt-0.5 text-blue-600 shrink-0" />
          <div className="flex-1">
            <h3 className="text-sm font-bold text-blue-800">
              Trigger Manual (Cron)
            </h3>
            <p className="mt-1 text-xs text-blue-700">
              Endpoint{" "}
              <code className="font-mono bg-blue-100 px-1 py-0.5 rounded">
                POST /api/cron/auto-article
              </code>{" "}
              diproteksi <code className="font-mono">Authorization: Bearer $CRON_SECRET</code>.
              Jalankan dari terminal VPS:
            </p>
            <pre className="mt-2 overflow-x-auto rounded-lg bg-blue-900 p-3 text-[11px] text-blue-100">
{`curl -X POST https://kartawarta.com/api/cron/auto-article \\
  -H "Authorization: Bearer $CRON_SECRET"`}
            </pre>
          </div>
        </div>
      </div>

      {/* Article list */}
      <div className="rounded-2xl border border-border bg-surface shadow-card overflow-hidden">
        <div className="border-b border-border bg-surface-secondary px-5 py-4 flex items-center justify-between">
          <h2 className="flex items-center gap-2 text-base font-bold text-txt-primary">
            <FileText size={16} className="text-primary" />
            Artikel Auto-Generated
          </h2>
          <span className="text-xs text-txt-muted">
            {articles.length} artikel
          </span>
        </div>
        {loadingArticles ? (
          <div className="py-12 text-center">
            <Loader2 size={24} className="mx-auto animate-spin text-primary" />
          </div>
        ) : articles.length === 0 ? (
          <div className="py-16 text-center">
            <Bot size={40} className="mx-auto text-border mb-3" />
            <p className="text-sm text-txt-secondary">
              Belum ada artikel auto-generated.
            </p>
            <p className="mt-1 text-xs text-txt-muted">
              Aktifkan toggle di atas atau jalankan cron manual.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="border-b border-border bg-surface-secondary">
                <tr>
                  <th className="px-5 py-3 text-left font-medium text-txt-secondary">
                    Judul
                  </th>
                  <th className="px-5 py-3 text-left font-medium text-txt-secondary">
                    Status
                  </th>
                  <th className="hidden sm:table-cell px-5 py-3 text-left font-medium text-txt-secondary">
                    Dibuat
                  </th>
                  <th className="px-5 py-3 text-right font-medium text-txt-secondary">
                    Aksi
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {articles.map((a) => (
                  <tr key={a.id} className="hover:bg-surface-secondary/50">
                    <td className="max-w-[280px] px-5 py-3">
                      <p className="truncate font-medium text-txt-primary">
                        {a.title}
                      </p>
                    </td>
                    <td className="px-5 py-3">
                      <span
                        className={`inline-flex items-center rounded-full px-3 py-0.5 text-xs font-medium ${
                          statusColors[a.status] ||
                          "bg-surface-tertiary text-txt-secondary"
                        }`}
                      >
                        {statusLabels[a.status] || a.status}
                      </span>
                    </td>
                    <td className="hidden sm:table-cell px-5 py-3 text-xs text-txt-secondary">
                      {formatDate(a.createdAt)}
                    </td>
                    <td className="px-5 py-3 text-right">
                      <div className="flex items-center justify-end gap-1">
                        <Link
                          href={`/panel/artikel/${a.id}/edit`}
                          className="btn-ghost rounded p-2"
                          title="Edit"
                        >
                          <Edit size={16} />
                        </Link>
                        <button
                          onClick={() => handleDelete(a.id)}
                          className="btn-ghost rounded p-2 hover:text-red-500"
                          title="Hapus"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <p className="mt-4 flex items-center gap-2 text-xs text-txt-muted">
        <Info size={12} />
        Auto-generation butuh: SystemSetting{" "}
        <code className="font-mono bg-surface-secondary px-1 py-0.5 rounded">
          auto_article_enabled
        </code>
        , row TargetKeyword aktif, dan AI provider (Anthropic / DeepSeek) di
        Pengaturan.
      </p>
    </div>
  );
}
