"use client";

/**
 * Auto Article Panel — SUPER_ADMIN only
 * - Master toggle (auto_article_enabled SystemSetting)
 * - List auto-generated articles (filter client-side by isAutoGenerated=true)
 * - Placeholder: TargetKeyword management (endpoint /api/target-keywords not yet available)
 */

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { redirect } from "next/navigation";
import {
  Bot,
  Sparkles,
  FileText,
  Edit,
  Trash2,
  Loader2,
  Info,
  RefreshCw,
  Terminal,
  Hash,
  Plus,
  Power,
  PowerOff,
  Upload,
  ArrowDownToLine,
  Eye,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { useToast } from "@/components/ui/Toast";
import { useConfirm } from "@/components/ui/ConfirmDialog";

interface Article {
  id: string;
  title: string;
  slug: string;
  status: string;
  isAutoGenerated?: boolean;
  createdAt: string;
  publishedAt: string | null;
}

interface Category {
  id: string;
  name: string;
  slug: string;
}

interface TargetKeyword {
  id: string;
  keyword: string;
  categoryId: string | null;
  category?: Category | null;
  priority: number;
  isActive: boolean;
  lastGeneratedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

const statusColors: Record<string, string> = {
  PUBLISHED: "bg-primary-light text-primary",
  IN_REVIEW: "bg-yellow-50 text-yellow-600",
  DRAFT: "bg-surface-tertiary text-txt-secondary",
  REJECTED: "bg-red-50 text-red-600",
  APPROVED: "bg-blue-50 text-blue-600",
  ARCHIVED: "bg-surface-tertiary text-txt-muted",
};

const statusLabels: Record<string, string> = {
  PUBLISHED: "Dipublikasi",
  IN_REVIEW: "Menunggu Review",
  DRAFT: "Draf",
  REJECTED: "Ditolak",
  APPROVED: "Disetujui",
  ARCHIVED: "Diarsipkan",
};

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("id-ID", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function AutoArtikelPage() {
  const { data: session, status: sessionStatus } = useSession();
  const userRole = session?.user?.role || "";
  const { success: showSuccess, error: showError } = useToast();
  const { confirm } = useConfirm();

  const [enabled, setEnabled] = useState<boolean>(false);
  const [intervalMinutes, setIntervalMinutes] = useState<number>(60);
  const [batchSize, setBatchSize] = useState<number>(1);
  const [savingInterval, setSavingInterval] = useState<boolean>(false);
  const [savingBatch, setSavingBatch] = useState<boolean>(false);
  const [loadingSettings, setLoadingSettings] = useState<boolean>(true);
  const [savingToggle, setSavingToggle] = useState<boolean>(false);
  const [articles, setArticles] = useState<Article[]>([]);
  const [loadingArticles, setLoadingArticles] = useState<boolean>(true);
  // Tab filter: pending = not yet PUBLISHED, published = live on the site
  const [publishTab, setPublishTab] = useState<"pending" | "published">("pending");
  const [page, setPage] = useState<number>(1);
  const PAGE_SIZE = 15;

  // Target keywords state
  const [keywords, setKeywords] = useState<TargetKeyword[]>([]);
  const [loadingKeywords, setLoadingKeywords] = useState<boolean>(true);
  const [keywordPage, setKeywordPage] = useState<number>(1);
  const KEYWORDS_PER_PAGE = 10;
  const [categories, setCategories] = useState<Category[]>([]);
  const [newKeyword, setNewKeyword] = useState<string>("");
  const [newCategoryId, setNewCategoryId] = useState<string>("");
  const [newPriority, setNewPriority] = useState<number>(0);
  const [creatingKw, setCreatingKw] = useState<boolean>(false);

  if (sessionStatus !== "loading" && session && userRole !== "SUPER_ADMIN") {
    redirect("/panel/dashboard");
  }

  const fetchSettings = useCallback(async () => {
    try {
      setLoadingSettings(true);
      const res = await fetch("/api/settings");
      if (res.ok) {
        const json = await res.json();
        setEnabled(String(json.data?.auto_article_enabled ?? "false") === "true");
        const iv = Number(json.data?.auto_article_interval_minutes ?? "60");
        setIntervalMinutes([5, 10, 15, 20, 30, 60].includes(iv) ? iv : 60);
        const bs = Math.floor(Number(json.data?.auto_article_batch_size ?? "1"));
        setBatchSize(Number.isFinite(bs) ? Math.min(20, Math.max(0, bs)) : 1);
      }
    } catch {
      /* non-critical */
    } finally {
      setLoadingSettings(false);
    }
  }, []);

  async function saveInterval(value: number) {
    try {
      setSavingInterval(true);
      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key: "auto_article_interval_minutes", value: String(value) }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menyimpan");
      setIntervalMinutes(value);
      showSuccess(`Interval di-set ke ${value} menit.`);
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menyimpan");
    } finally {
      setSavingInterval(false);
    }
  }

  async function saveBatch(value: number) {
    const clamped = Math.min(20, Math.max(0, Math.floor(value)));
    try {
      setSavingBatch(true);
      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key: "auto_article_batch_size", value: String(clamped) }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menyimpan");
      setBatchSize(clamped);
      showSuccess(clamped === 0 ? "Batch di-set 0 — generation pause." : `Batch di-set ke ${clamped} artikel/run.`);
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menyimpan");
    } finally {
      setSavingBatch(false);
    }
  }

  const fetchArticles = useCallback(async () => {
    try {
      setLoadingArticles(true);
      // Server-side filter via ?origin=auto so we don't waste a 500-row
      // payload on manual articles we'd just discard. Limit raised to 5000
      // to cover the long tail (~684 today and growing daily via cron).
      const res = await fetch("/api/articles?origin=auto&status=ALL&limit=5000");
      if (res.ok) {
        const json = await res.json();
        setArticles((json.data?.articles || []) as Article[]);
      }
    } catch {
      /* non-critical */
    } finally {
      setLoadingArticles(false);
    }
  }, []);

  const fetchKeywords = useCallback(async () => {
    try {
      setLoadingKeywords(true);
      const res = await fetch("/api/target-keywords");
      if (res.ok) {
        const json = await res.json();
        setKeywords(Array.isArray(json.data) ? json.data : []);
      }
    } catch {
      /* */
    } finally {
      setLoadingKeywords(false);
    }
  }, []);

  const fetchCategories = useCallback(async () => {
    try {
      const res = await fetch("/api/categories");
      if (res.ok) {
        const json = await res.json();
        setCategories(Array.isArray(json.data) ? json.data : []);
      }
    } catch {
      /* */
    }
  }, []);

  useEffect(() => {
    fetchSettings();
    fetchArticles();
    fetchKeywords();
    fetchCategories();
  }, [fetchSettings, fetchArticles, fetchKeywords, fetchCategories]);

  // Snap pagination back when the keyword count drops (e.g. last item on
  // current page deleted) so we never render an empty page.
  useEffect(() => {
    const totalPages = Math.max(1, Math.ceil(keywords.length / KEYWORDS_PER_PAGE));
    if (keywordPage > totalPages) setKeywordPage(totalPages);
  }, [keywords.length, keywordPage]);

  async function handleCreateKeyword() {
    const trimmed = newKeyword.trim();
    if (trimmed.length < 2) {
      showError("Keyword minimal 2 karakter.");
      return;
    }
    try {
      setCreatingKw(true);
      const res = await fetch("/api/target-keywords", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          keyword: trimmed,
          categoryId: newCategoryId || null,
          priority: Number.isFinite(newPriority) ? newPriority : 0,
        }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menambah keyword");
      showSuccess("Keyword berhasil ditambahkan.");
      setNewKeyword("");
      setNewCategoryId("");
      setNewPriority(0);
      fetchKeywords();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menambah keyword");
    } finally {
      setCreatingKw(false);
    }
  }

  async function handleToggleKeyword(kw: TargetKeyword) {
    try {
      const res = await fetch("/api/target-keywords", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: kw.id, isActive: !kw.isActive }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal mengubah status");
      showSuccess(
        !kw.isActive ? "Keyword diaktifkan." : "Keyword dinonaktifkan.",
      );
      fetchKeywords();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal");
    }
  }

  async function handleUpdatePriority(kw: TargetKeyword, priority: number) {
    if (priority < 0 || priority > 100) {
      showError("Priority harus 0–100");
      return;
    }
    try {
      const res = await fetch("/api/target-keywords", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: kw.id, priority }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal");
      fetchKeywords();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal");
    }
  }

  async function handleDeleteKeyword(kw: TargetKeyword) {
    const ok = await confirm({
      title: "Hapus keyword",
      message: `Yakin hapus keyword "${kw.keyword}"?`,
      variant: "danger",
    });
    if (!ok) return;
    try {
      const res = await fetch(
        `/api/target-keywords?id=${encodeURIComponent(kw.id)}`,
        { method: "DELETE" },
      );
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menghapus");
      showSuccess("Keyword dihapus.");
      fetchKeywords();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menghapus");
    }
  }

  async function handleToggle() {
    try {
      setSavingToggle(true);
      const newValue = !enabled;
      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          key: "auto_article_enabled",
          value: newValue ? "true" : "false",
        }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menyimpan");
      setEnabled(newValue);
      showSuccess(
        newValue ? "Auto Artikel diaktifkan." : "Auto Artikel dinonaktifkan.",
      );
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menyimpan");
    } finally {
      setSavingToggle(false);
    }
  }

  async function handlePublish(id: string, title: string) {
    const ok = await confirm({
      title: "Publikasikan artikel",
      message: `Publikasikan "${title}" sekarang? Artikel akan langsung tampil di publik.`,
      variant: "warning",
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/articles/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "PUBLISHED" }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal publikasi");
      showSuccess("Artikel dipublikasi.");
      fetchArticles();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal publikasi");
    }
  }

  async function handleTakedown(id: string, title: string) {
    const ok = await confirm({
      title: "Takedown artikel",
      message: `Turunkan "${title}" dari publik? Status kembali ke DRAFT — bisa dipublish ulang nanti.`,
      variant: "warning",
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/articles/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "DRAFT" }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal takedown");
      showSuccess("Artikel di-takedown ke DRAFT.");
      fetchArticles();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal takedown");
    }
  }

  async function handleDelete(id: string) {
    const ok = await confirm({
      title: "Hapus draf",
      message: "Yakin ingin menghapus draf auto-generated ini?",
      variant: "danger",
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/articles/${id}`, { method: "DELETE" });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || "Gagal menghapus");
      showSuccess("Draf berhasil dihapus.");
      fetchArticles();
    } catch (err) {
      showError(err instanceof Error ? err.message : "Gagal menghapus");
    }
  }

  const stats = {
    total: articles.length,
    draft: articles.filter((a) => a.status === "DRAFT").length,
    review: articles.filter((a) => a.status === "IN_REVIEW").length,
    published: articles.filter((a) => a.status === "PUBLISHED").length,
  };

  if (sessionStatus === "loading") {
    return (
      <div className="flex min-h-[40vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
      </div>
    );
  }

  return (
    <div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <Bot size={24} className="text-primary" />
            <h1 className="text-xl sm:text-3xl font-bold text-txt-primary">
              Auto Artikel
            </h1>
          </div>
          <p className="mt-1 text-sm text-txt-secondary">
            Generator artikel otomatis via AI berdasarkan Target Keyword.
          </p>
        </div>
        <button
          onClick={() => {
            fetchSettings();
            fetchArticles();
            fetchKeywords();
          }}
          className="btn-ghost flex items-center gap-2 px-3 py-2.5 text-sm"
        >
          <RefreshCw size={14} /> Refresh
        </button>
      </div>

      {/* Master Toggle */}
      <div className="mb-6 rounded-2xl border border-border bg-surface p-5 shadow-card">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-light">
              <Sparkles size={18} className="text-primary" />
            </div>
            <div>
              <h2 className="text-base font-bold text-txt-primary">
                Auto Generation
              </h2>
              <p className="text-xs text-txt-secondary">
                {enabled
                  ? batchSize === 0
                    ? `Aktif tapi batch = 0 (pause). Cron tetap dipanggil tiap ${intervalMinutes} menit.`
                    : `Cron akan men-generate ${batchSize} artikel setiap ${intervalMinutes} menit.`
                  : "Nonaktif — cron di-skip meskipun dipicu."}
              </p>
            </div>
          </div>
          <button
            onClick={handleToggle}
            disabled={loadingSettings || savingToggle}
            className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors disabled:opacity-50 ${
              enabled ? "bg-primary" : "bg-surface-tertiary"
            }`}
            aria-label="Toggle auto-article"
          >
            <span
              className={`inline-block h-5 w-5 transform rounded-full bg-white shadow transition-transform ${
                enabled ? "translate-x-6" : "translate-x-1"
              }`}
            />
          </button>
        </div>

        {/* Interval + batch size controls */}
        <div className="mt-5 grid grid-cols-1 gap-4 border-t border-border pt-5 sm:grid-cols-2">
          <div>
            <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-txt-secondary">
              Interval Generate
            </label>
            <select
              value={intervalMinutes}
              onChange={(e) => saveInterval(Number(e.target.value))}
              disabled={loadingSettings || savingInterval}
              className="input w-full px-3 py-2 text-sm disabled:opacity-50"
            >
              <option value={5}>Setiap 5 menit</option>
              <option value={10}>Setiap 10 menit</option>
              <option value={15}>Setiap 15 menit</option>
              <option value={20}>Setiap 20 menit</option>
              <option value={30}>Setiap 30 menit</option>
              <option value={60}>Setiap 1 jam</option>
            </select>
            <p className="mt-1 text-xs text-txt-muted">
              Cron VPS dipanggil tiap 5 menit; throttle endpoint memastikan generate hanya jalan sesuai pilihan ini.
            </p>
          </div>

          <div>
            <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-txt-secondary">
              Jumlah Artikel per Run
            </label>
            <div className="flex items-center gap-2">
              <input
                type="number"
                min={0}
                max={20}
                step={1}
                value={batchSize}
                onChange={(e) => setBatchSize(Math.min(20, Math.max(0, Math.floor(Number(e.target.value) || 0))))}
                onBlur={(e) => saveBatch(Math.floor(Number(e.target.value) || 0))}
                disabled={loadingSettings || savingBatch}
                className="input w-24 px-3 py-2 text-sm disabled:opacity-50"
              />
              <span className="text-xs text-txt-secondary">artikel (0–20)</span>
            </div>
            <p className="mt-1 text-xs text-txt-muted">
              0 = pause sementara tanpa nonaktifkan toggle. 20 = batch maksimum per cycle.
            </p>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Total Auto</p>
          <p className="mt-1 text-2xl font-extrabold text-txt-primary">
            {stats.total}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Draf</p>
          <p className="mt-1 text-2xl font-extrabold text-txt-secondary">
            {stats.draft}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Review</p>
          <p className="mt-1 text-2xl font-extrabold text-yellow-600">
            {stats.review}
          </p>
        </div>
        <div className="rounded-2xl border border-border bg-surface p-4 shadow-card">
          <p className="text-xs text-txt-secondary">Dipublikasi</p>
          <p className="mt-1 text-2xl font-extrabold text-primary">
            {stats.published}
          </p>
        </div>
      </div>

      {/* Target Keywords Manager */}
      <div className="mb-6 rounded-2xl border border-border bg-surface shadow-card overflow-hidden">
        <div className="border-b border-border bg-surface-secondary px-5 py-4 flex items-center justify-between">
          <h2 className="flex items-center gap-2 text-base font-bold text-txt-primary">
            <Hash size={16} className="text-primary" />
            Target Keyword
          </h2>
          <span className="text-xs text-txt-muted">
            {keywords.length} keyword
          </span>
        </div>

        {/* Create form */}
        <div className="border-b border-border bg-surface-secondary/40 px-5 py-4">
          <div className="grid gap-2 sm:grid-cols-[1fr_180px_100px_auto]">
            <input
              type="text"
              className="input py-2 text-sm"
              placeholder="Keyword baru (mis. RUU KUHAP 2026)"
              value={newKeyword}
              onChange={(e) => setNewKeyword(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleCreateKeyword();
              }}
            />
            <select
              className="input py-2 text-sm"
              value={newCategoryId}
              onChange={(e) => setNewCategoryId(e.target.value)}
            >
              <option value="">— Tanpa kategori —</option>
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </select>
            <input
              type="number"
              min={0}
              max={100}
              className="input py-2 text-sm"
              placeholder="Priority"
              value={newPriority}
              onChange={(e) =>
                setNewPriority(parseInt(e.target.value) || 0)
              }
            />
            <button
              onClick={handleCreateKeyword}
              disabled={creatingKw}
              className="btn-primary flex items-center gap-2 rounded-md px-4 py-2 text-sm font-semibold disabled:opacity-50"
            >
              {creatingKw ? (
                <Loader2 size={14} className="animate-spin" />
              ) : (
                <Plus size={14} />
              )}
              Tambah
            </button>
          </div>
          <p className="mt-2 text-[11px] text-txt-muted">
            Cron auto-article akan memilih random dari top 10 priority keyword
            aktif.
          </p>
        </div>

        {loadingKeywords ? (
          <div className="py-12 text-center">
            <Loader2 size={24} className="mx-auto animate-spin text-primary" />
          </div>
        ) : keywords.length === 0 ? (
          <div className="py-12 text-center">
            <Hash size={36} className="mx-auto text-border mb-3" />
            <p className="text-sm text-txt-secondary">
              Belum ada target keyword.
            </p>
            <p className="mt-1 text-xs text-txt-muted">
              Tambahkan minimal satu keyword di form atas.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="border-b border-border bg-surface-secondary">
                <tr>
                  <th className="px-5 py-3 text-left font-medium text-txt-secondary">
                    Keyword
                  </th>
                  <th className="hidden sm:table-cell px-5 py-3 text-left font-medium text-txt-secondary">
                    Kategori
                  </th>
                  <th className="px-5 py-3 text-right font-medium text-txt-secondary">
                    Priority
                  </th>
                  <th className="px-5 py-3 text-right font-medium text-txt-secondary">
                    Status
                  </th>
                  <th className="px-5 py-3 text-right font-medium text-txt-secondary">
                    Aksi
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {keywords
                  .slice(
                    (keywordPage - 1) * KEYWORDS_PER_PAGE,
                    keywordPage * KEYWORDS_PER_PAGE,
                  )
                  .map((kw) => (
                  <tr
                    key={kw.id}
                    className={`hover:bg-surface-secondary/50 ${
                      !kw.isActive ? "opacity-50" : ""
                    }`}
                  >
                    <td className="px-5 py-3 font-medium text-txt-primary">
                      {kw.keyword}
                      {kw.lastGeneratedAt && (
                        <p className="mt-0.5 text-[10px] text-txt-muted">
                          terakhir generate: {formatDate(kw.lastGeneratedAt)}
                        </p>
                      )}
                    </td>
                    <td className="hidden sm:table-cell px-5 py-3 text-xs text-txt-secondary">
                      {kw.category?.name || "—"}
                    </td>
                    <td className="px-5 py-3 text-right">
                      <input
                        type="number"
                        min={0}
                        max={100}
                        defaultValue={kw.priority}
                        onBlur={(e) => {
                          const v = parseInt(e.target.value) || 0;
                          if (v !== kw.priority) {
                            handleUpdatePriority(kw, v);
                          }
                        }}
                        className="input w-16 py-1 text-right text-xs"
                      />
                    </td>
                    <td className="px-5 py-3 text-right">
                      <span
                        className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-[10px] font-medium ${
                          kw.isActive
                            ? "bg-primary-light text-primary"
                            : "bg-surface-tertiary text-txt-secondary"
                        }`}
                      >
                        {kw.isActive ? "Aktif" : "Nonaktif"}
                      </span>
                    </td>
                    <td className="px-5 py-3 text-right">
                      <div className="flex items-center justify-end gap-1">
                        <button
                          onClick={() => handleToggleKeyword(kw)}
                          className="btn-ghost rounded p-2"
                          title={kw.isActive ? "Nonaktifkan" : "Aktifkan"}
                        >
                          {kw.isActive ? (
                            <PowerOff size={14} />
                          ) : (
                            <Power size={14} />
                          )}
                        </button>
                        <button
                          onClick={() => handleDeleteKeyword(kw)}
                          className="btn-ghost rounded p-2 hover:text-red-500"
                          title="Hapus"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {keywords.length > KEYWORDS_PER_PAGE && (
              <div className="flex items-center justify-between border-t border-border bg-surface-secondary/40 px-5 py-3 text-xs">
                <span className="text-txt-secondary">
                  Menampilkan{" "}
                  <span className="font-semibold text-txt-primary">
                    {(keywordPage - 1) * KEYWORDS_PER_PAGE + 1}
                  </span>
                  –
                  <span className="font-semibold text-txt-primary">
                    {Math.min(keywordPage * KEYWORDS_PER_PAGE, keywords.length)}
                  </span>{" "}
                  dari{" "}
                  <span className="font-semibold text-txt-primary">
                    {keywords.length}
                  </span>{" "}
                  keyword
                </span>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => setKeywordPage((p) => Math.max(1, p - 1))}
                    disabled={keywordPage === 1}
                    className="btn-ghost flex items-center gap-1 rounded px-2 py-1 disabled:opacity-30"
                    aria-label="Halaman sebelumnya"
                  >
                    <ChevronLeft size={14} />
                    Prev
                  </button>
                  <span className="px-2 font-semibold text-txt-primary">
                    {keywordPage} / {Math.ceil(keywords.length / KEYWORDS_PER_PAGE)}
                  </span>
                  <button
                    onClick={() =>
                      setKeywordPage((p) =>
                        Math.min(
                          Math.ceil(keywords.length / KEYWORDS_PER_PAGE),
                          p + 1,
                        ),
                      )
                    }
                    disabled={
                      keywordPage >=
                      Math.ceil(keywords.length / KEYWORDS_PER_PAGE)
                    }
                    className="btn-ghost flex items-center gap-1 rounded px-2 py-1 disabled:opacity-30"
                    aria-label="Halaman berikutnya"
                  >
                    Next
                    <ChevronRight size={14} />
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Trigger Info */}
      <div className="mb-6 rounded-2xl border border-blue-200 bg-blue-50 p-5">
        <div className="flex items-start gap-3">
          <Terminal size={18} className="mt-0.5 text-blue-600 shrink-0" />
          <div className="flex-1">
            <h3 className="text-sm font-bold text-blue-800">
              Trigger Manual (Cron)
            </h3>
            <p className="mt-1 text-xs text-blue-700">
              Endpoint{" "}
              <code className="font-mono bg-blue-100 px-1 py-0.5 rounded">
                POST /api/cron/auto-article
              </code>{" "}
              diproteksi <code className="font-mono">Authorization: Bearer $CRON_SECRET</code>.
              Jalankan dari terminal VPS:
            </p>
            <pre className="mt-2 overflow-x-auto rounded-lg bg-blue-900 p-3 text-[11px] text-blue-100">
{`curl -X POST https://kartawarta.com/api/cron/auto-article \\
  -H "Authorization: Bearer $CRON_SECRET"`}
            </pre>
          </div>
        </div>
      </div>

      {/* Article list */}
      <div className="rounded-2xl border border-border bg-surface shadow-card overflow-hidden">
        <div className="border-b border-border bg-surface-secondary px-5 py-4 flex items-center justify-between flex-wrap gap-3">
          <h2 className="flex items-center gap-2 text-base font-bold text-txt-primary">
            <FileText size={16} className="text-primary" />
            Artikel Auto-Generated
          </h2>
          <span className="text-xs text-txt-muted">
            {articles.length} artikel
          </span>
        </div>

        {/* Publish-status tabs */}
        {(() => {
          const pendingCount = articles.filter((a) => a.status !== "PUBLISHED").length;
          const publishedCount = articles.filter((a) => a.status === "PUBLISHED").length;
          return (
            <div className="flex border-b border-border bg-surface-secondary/40">
              <button
                type="button"
                onClick={() => { setPublishTab("pending"); setPage(1); }}
                className={`flex-1 px-5 py-3 text-sm font-semibold transition-colors ${
                  publishTab === "pending"
                    ? "bg-surface text-primary border-b-2 border-primary"
                    : "text-txt-secondary hover:bg-surface/40"
                }`}
              >
                Belum Terpublikasi
                <span className="ml-2 rounded-full bg-yellow-50 px-2 py-0.5 text-[10px] font-bold text-yellow-700">
                  {pendingCount}
                </span>
              </button>
              <button
                type="button"
                onClick={() => { setPublishTab("published"); setPage(1); }}
                className={`flex-1 px-5 py-3 text-sm font-semibold transition-colors ${
                  publishTab === "published"
                    ? "bg-surface text-primary border-b-2 border-primary"
                    : "text-txt-secondary hover:bg-surface/40"
                }`}
              >
                Terpublikasi
                <span className="ml-2 rounded-full bg-primary-light px-2 py-0.5 text-[10px] font-bold text-primary">
                  {publishedCount}
                </span>
              </button>
            </div>
          );
        })()}

        {(() => {
          const visible =
            publishTab === "published"
              ? articles.filter((a) => a.status === "PUBLISHED")
              : articles.filter((a) => a.status !== "PUBLISHED");
          if (loadingArticles) {
            return (
              <div className="py-12 text-center">
                <Loader2 size={24} className="mx-auto animate-spin text-primary" />
              </div>
            );
          }
          if (visible.length === 0) {
            return (
              <div className="py-16 text-center">
                <Bot size={40} className="mx-auto text-border mb-3" />
                <p className="text-sm text-txt-secondary">
                  {publishTab === "published"
                    ? "Belum ada artikel auto-generated yang dipublikasi."
                    : "Tidak ada artikel auto-generated yang menunggu publikasi."}
                </p>
              </div>
            );
          }
          return null;
        })()}

        {!loadingArticles && (() => {
          const visibleAll =
            publishTab === "published"
              ? articles.filter((a) => a.status === "PUBLISHED")
              : articles.filter((a) => a.status !== "PUBLISHED");
          if (visibleAll.length === 0) return null;
          const totalPages = Math.max(1, Math.ceil(visibleAll.length / PAGE_SIZE));
          const safePage = Math.min(page, totalPages);
          const start = (safePage - 1) * PAGE_SIZE;
          const visible = visibleAll.slice(start, start + PAGE_SIZE);
          return (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="border-b border-border bg-surface-secondary">
                <tr>
                  <th className="px-5 py-3 text-left font-medium text-txt-secondary">
                    Judul
                  </th>
                  <th className="px-5 py-3 text-left font-medium text-txt-secondary">
                    Status
                  </th>
                  <th className="hidden sm:table-cell px-5 py-3 text-left font-medium text-txt-secondary">
                    Dibuat
                  </th>
                  <th className="px-5 py-3 text-right font-medium text-txt-secondary">
                    Aksi
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {visible.map((a) => (
                  <tr key={a.id} className="hover:bg-surface-secondary/50">
                    <td className="max-w-[280px] px-5 py-3">
                      <Link
                        href={`/panel/artikel/${a.id}/edit`}
                        className="block truncate font-medium text-txt-primary hover:text-primary transition-colors"
                        title="Buka di editor"
                      >
                        {a.title}
                      </Link>
                    </td>
                    <td className="px-5 py-3">
                      <span
                        className={`inline-flex items-center rounded-full px-3 py-0.5 text-xs font-medium ${
                          statusColors[a.status] ||
                          "bg-surface-tertiary text-txt-secondary"
                        }`}
                      >
                        {statusLabels[a.status] || a.status}
                      </span>
                    </td>
                    <td className="hidden sm:table-cell px-5 py-3 text-xs text-txt-secondary">
                      {formatDate(a.createdAt)}
                    </td>
                    <td className="px-5 py-3 text-right">
                      <div className="flex items-center justify-end gap-1">
                        {a.status === "PUBLISHED" && a.slug && (
                          <a
                            href={`/berita/${a.slug}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="btn-ghost rounded p-2 hover:text-primary"
                            title="Lihat artikel di publik"
                            aria-label="Lihat artikel"
                          >
                            <Eye size={16} />
                          </a>
                        )}
                        {a.status === "PUBLISHED" ? (
                          <button
                            onClick={() => handleTakedown(a.id, a.title)}
                            className="btn-ghost rounded p-2 hover:text-yellow-700"
                            title="Takedown — kembalikan ke DRAFT"
                            aria-label="Takedown artikel"
                          >
                            <ArrowDownToLine size={16} />
                          </button>
                        ) : (
                          <button
                            onClick={() => handlePublish(a.id, a.title)}
                            className="btn-ghost rounded p-2 hover:text-primary"
                            title="Publikasi sekarang"
                            aria-label="Publikasi artikel"
                          >
                            <Upload size={16} />
                          </button>
                        )}
                        <Link
                          href={`/panel/artikel/${a.id}/edit`}
                          className="btn-ghost rounded p-2"
                          title="Edit"
                        >
                          <Edit size={16} />
                        </Link>
                        <button
                          onClick={() => handleDelete(a.id)}
                          className="btn-ghost rounded p-2 hover:text-red-500"
                          title="Hapus"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {totalPages > 1 && (
              <div className="flex items-center justify-between gap-3 border-t border-border bg-surface-secondary/40 px-5 py-3">
                <span className="text-xs text-txt-muted">
                  Halaman {safePage} dari {totalPages} · {visibleAll.length} artikel
                </span>
                <div className="flex items-center gap-1">
                  <button
                    type="button"
                    onClick={() => setPage(Math.max(1, safePage - 1))}
                    disabled={safePage <= 1}
                    className="rounded-md border border-border bg-surface px-3 py-1.5 text-xs font-medium text-txt-secondary hover:bg-surface-secondary disabled:opacity-30"
                  >
                    Sebelumnya
                  </button>
                  <button
                    type="button"
                    onClick={() => setPage(Math.min(totalPages, safePage + 1))}
                    disabled={safePage >= totalPages}
                    className="rounded-md border border-border bg-surface px-3 py-1.5 text-xs font-medium text-txt-secondary hover:bg-surface-secondary disabled:opacity-30"
                  >
                    Selanjutnya
                  </button>
                </div>
              </div>
            )}
          </div>
          );
        })()}
      </div>

      <p className="mt-4 flex items-center gap-2 text-xs text-txt-muted">
        <Info size={12} />
        Auto-generation butuh: SystemSetting{" "}
        <code className="font-mono bg-surface-secondary px-1 py-0.5 rounded">
          auto_article_enabled
        </code>
        , row TargetKeyword aktif, dan AI provider (Anthropic / DeepSeek) di
        Pengaturan.
      </p>
    </div>
  );
}
