/**
 * POST/GET /api/cron/auto-article
 *
 * Cron endpoint: auto-generate ONE article draft via AI from a random
 * active `TargetKeyword`. Protected by `Authorization: Bearer ${CRON_SECRET}`.
 *
 * Flow:
 *   1. Check `SystemSetting.auto_article_enabled === "true"` — else skip
 *   2. Pick random active keyword (priority desc, random from top 10)
 *   3. Call `callAI({feature: "article_draft", ...})` — expect JSON output
 *   4. Parse JSON (tolerate markdown code fences); fallback to plain title+content
 *   5. Resolve authorId (first SUPER_ADMIN) + categoryId (suggested match, else first)
 *   6. Create Article status=DRAFT, isAutoGenerated=true with unique slug
 *   7. Update keyword.lastGeneratedAt
 *   8. Return summary
 *
 * All errors are trapped: endpoint always returns HTTP 200 with
 * `{success:false, error}` on failure so cron doesn't retry-spam.
 *
 * Recommend invocation: every 1 hour.
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { callAI } from "@/lib/ai-client";
import { slugify } from "@/lib/utils";
import { sanitizeHtml } from "@/lib/sanitize";
import { verifyCronSecret, errorResponse } from "@/lib/api-utils";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

interface GeneratedArticle {
  title: string;
  excerpt: string;
  content: string;
  suggestedCategoryId?: string | null;
  suggestedTags?: string[];
}

interface RelatedArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string | null;
  content: string;
  publishedAt: Date | null;
  category: { name: string } | null;
}

/**
 * Find published articles that already mention the keyword.
 * Searches title/excerpt/content (Postgres ILIKE — case-insensitive, prefix-free).
 * Ranks by recency, then view count.
 *
 * Returns at most `limit` items with content trimmed to a usable size for
 * AI context (`MAX_CONTEXT_CHARS_PER_ARTICLE`).
 */
async function findRelatedArticles(
  keyword: string,
  limit: number,
): Promise<RelatedArticle[]> {
  const MAX_CONTEXT_CHARS_PER_ARTICLE = 2_500;
  const articles = await prisma.article.findMany({
    where: {
      status: "PUBLISHED",
      isAutoGenerated: false, // synthesise from human-written sources only
      OR: [
        { title: { contains: keyword, mode: "insensitive" } },
        { excerpt: { contains: keyword, mode: "insensitive" } },
        { content: { contains: keyword, mode: "insensitive" } },
      ],
    },
    orderBy: [{ publishedAt: "desc" }, { viewCount: "desc" }],
    take: limit,
    select: {
      id: true,
      slug: true,
      title: true,
      excerpt: true,
      content: true,
      publishedAt: true,
      category: { select: { name: true } },
    },
  });
  return articles.map((a) => ({
    ...a,
    content: stripHtml(a.content).slice(0, MAX_CONTEXT_CHARS_PER_ARTICLE),
  }));
}

function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  // Remove leading ```json / ```
  const fenced = trimmed.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  if (fenced) return fenced[1].trim();
  return trimmed;
}

function tryParseJson(raw: string): GeneratedArticle | null {
  try {
    const cleaned = stripCodeFence(raw);
    const parsed = JSON.parse(cleaned);
    if (
      parsed &&
      typeof parsed === "object" &&
      typeof parsed.title === "string" &&
      typeof parsed.content === "string"
    ) {
      return {
        title: parsed.title.trim(),
        excerpt:
          typeof parsed.excerpt === "string" ? parsed.excerpt.trim() : "",
        content: parsed.content.trim(),
        suggestedCategoryId:
          typeof parsed.suggestedCategoryId === "string"
            ? parsed.suggestedCategoryId.trim()
            : null,
        suggestedTags: Array.isArray(parsed.suggestedTags)
          ? parsed.suggestedTags
              .filter((t: unknown): t is string => typeof t === "string")
              .slice(0, 10)
          : [],
      };
    }
  } catch {
    // fall through
  }
  return null;
}

function fallbackParse(raw: string, keyword: string): GeneratedArticle {
  // Pull first non-empty line as title, rest as content.
  const lines = raw
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const title = lines[0]
    ? lines[0].replace(/^#+\s*/, "").slice(0, 120)
    : `Kabar Terkini: ${keyword}`;
  const body = lines.slice(1).join("\n\n") || raw.trim();
  const contentHtml = body
    .split(/\n{2,}/)
    .map((p) => `<p>${p.trim()}</p>`)
    .join("\n");
  return {
    title,
    excerpt: body.slice(0, 180).replace(/\s+\S*$/, ""),
    content: contentHtml || `<p>${raw.slice(0, 800)}</p>`,
    suggestedCategoryId: null,
    suggestedTags: [],
  };
}

async function uniqueSlug(base: string): Promise<string> {
  const root = slugify(base).slice(0, 90) || "artikel";
  const existing = await prisma.article.findUnique({
    where: { slug: root },
    select: { id: true },
  });
  if (!existing) return root;
  const suffix = Math.random().toString(36).slice(2, 8);
  return `${root}-${suffix}`;
}

async function handler(req: NextRequest) {
  const started = Date.now();
  try {
    try { verifyCronSecret(req); } catch (e) { return errorResponse(e); }

    // 1. Toggle check
    let enabled = false;
    try {
      const setting = await prisma.systemSetting.findUnique({
        where: { key: "auto_article_enabled" },
      });
      enabled = setting?.value === "true";
    } catch {
      // DB unavailable — treat as disabled
      enabled = false;
    }
    if (!enabled) {
      return NextResponse.json(
        {
          success: true,
          skipped: "disabled",
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    // 2. Pick keyword
    const keywords = await prisma.targetKeyword.findMany({
      where: { isActive: true },
      orderBy: { priority: "desc" },
      take: 10,
    });
    if (keywords.length === 0) {
      return NextResponse.json(
        {
          success: true,
          skipped: "no-active-keywords",
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }
    const kw = keywords[Math.floor(Math.random() * keywords.length)];

    // 3. Find related original articles to ground the draft.
    //    Only when at least one source exists, the AI synthesises an
    //    update/follow-up. With no sources we still allow a generic draft
    //    so the cron doesn't stall on niche keywords.
    const relatedArticles = await findRelatedArticles(kw.keyword, 5);

    let referenceBlock = "";
    if (relatedArticles.length > 0) {
      referenceBlock = `\n\nSUMBER ARTIKEL ORISINIL (gunakan sebagai dasar — sintesis, jangan plagiat):\n` +
        relatedArticles
          .map((a, i) => {
            const date = a.publishedAt
              ? new Date(a.publishedAt).toLocaleDateString("id-ID", {
                  day: "numeric",
                  month: "long",
                  year: "numeric",
                })
              : "";
            const head = `[${i + 1}] "${a.title}" (${a.category?.name ?? "Umum"}, ${date})`;
            const summary = a.excerpt ? `Ringkasan: ${a.excerpt}` : "";
            const body = `Isi: ${a.content}`;
            return [head, summary, body].filter(Boolean).join("\n");
          })
          .join("\n\n---\n\n");
    }

    const groundingInstruction =
      relatedArticles.length > 0
        ? `Tugas: tulis follow-up / update artikel berita berdasarkan sumber-sumber di atas. Sintesiskan informasi terbaru, hindari menyalin kalimat persis. Sebutkan kembali fakta penting yang masih relevan, tambahkan konteks/perkembangan, dan jaga akurasi nama, jabatan, angka, kutipan dari sumber. Jika ada perbedaan antar sumber, sajikan secara berimbang.`
        : `Tugas: tulis artikel berita standar tentang topik tersebut. Karena belum ada artikel orisinil terkait di arsip, fokuskan pada konteks umum dan hindari klaim spesifik tanpa dasar.`;

    const userPrompt = `Tulis draft artikel berita jurnalistik dalam Bahasa Indonesia tentang: "${kw.keyword}".

${groundingInstruction}${referenceBlock}

Format output WAJIB JSON valid (tanpa teks lain di luar JSON):
{
  "title": "judul menarik 50-80 karakter",
  "excerpt": "ringkasan 150-200 karakter",
  "content": "body artikel 600-800 kata, HTML dengan <p>, <h2>, <ul> yang sesuai",
  "suggestedCategoryId": null,
  "suggestedTags": ["tag1", "tag2", "tag3"]
}

Konteks: Kartawarta adalah platform media hukum digital untuk Kota Bandung. Tulis objektif, netral, lead kuat 5W+1H, hindari klaim tanpa dasar.`;

    let aiResult;
    try {
      aiResult = await callAI({
        feature: "article_draft",
        userPrompt,
        maxTokens: 2000,
        temperature: 0.7,
      });
    } catch (e) {
      return NextResponse.json(
        {
          success: false,
          error: `AI call failed: ${e instanceof Error ? e.message : String(e)}`,
          keyword: kw.keyword,
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    // 4. Parse
    const parsed =
      tryParseJson(aiResult.text) ?? fallbackParse(aiResult.text, kw.keyword);

    // 5. Resolve author + category
    const admin = await prisma.user.findFirst({
      where: { role: "SUPER_ADMIN" },
      orderBy: { createdAt: "asc" },
      select: { id: true },
    });
    if (!admin) {
      return NextResponse.json(
        {
          success: false,
          error: "No SUPER_ADMIN user exists to own the draft",
          keyword: kw.keyword,
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    let categoryId: string | null = null;
    if (parsed.suggestedCategoryId) {
      const cat = await prisma.category.findFirst({
        where: {
          OR: [
            { id: parsed.suggestedCategoryId },
            { slug: parsed.suggestedCategoryId },
            { name: parsed.suggestedCategoryId },
          ],
        },
        select: { id: true },
      });
      categoryId = cat?.id ?? null;
    }
    if (!categoryId && kw.categoryId) {
      categoryId = kw.categoryId;
    }
    if (!categoryId) {
      const fallbackCat = await prisma.category.findFirst({
        orderBy: { order: "asc" },
        select: { id: true },
      });
      categoryId = fallbackCat?.id ?? null;
    }
    if (!categoryId) {
      return NextResponse.json(
        {
          success: false,
          error: "No category exists to attach draft to",
          keyword: kw.keyword,
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    // 6. Create article — link primary source article when grounding was used.
    const primarySourceId = relatedArticles[0]?.id ?? null;
    const slug = await uniqueSlug(parsed.title);
    let article;
    try {
      article = await prisma.article.create({
        data: {
          title: parsed.title.slice(0, 250),
          slug,
          content: sanitizeHtml(parsed.content),
          excerpt: parsed.excerpt.slice(0, 500) || null,
          status: "DRAFT",
          isAutoGenerated: true,
          sourceArticleId: primarySourceId,
          authorId: admin.id,
          categoryId,
        },
        select: { id: true, slug: true, title: true },
      });
    } catch (e) {
      return NextResponse.json(
        {
          success: false,
          error: `DB create failed: ${e instanceof Error ? e.message : String(e)}`,
          keyword: kw.keyword,
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    // 7. Update keyword.lastGeneratedAt (best-effort)
    try {
      await prisma.targetKeyword.update({
        where: { id: kw.id },
        data: { lastGeneratedAt: new Date() },
      });
    } catch {
      // swallow
    }

    // Audit log (best-effort, user 'system' may not exist)
    try {
      await prisma.auditLog.create({
        data: {
          userId: admin.id,
          action: "CRON_AUTO_ARTICLE",
          entity: "article",
          entityId: article.id,
          detail: JSON.stringify({
            keyword: kw.keyword,
            provider: aiResult.provider,
            tokens: aiResult.totalTokens,
            sourcesUsed: relatedArticles.length,
            sourceSlugs: relatedArticles.map((a) => a.slug),
          }),
        },
      });
    } catch {
      // swallow
    }

    return NextResponse.json(
      {
        success: true,
        articleId: article.id,
        slug: article.slug,
        titleGenerated: article.title,
        keyword: kw.keyword,
        provider: aiResult.provider,
        tokens: aiResult.totalTokens,
        sourcesUsed: relatedArticles.length,
        sourceSlugs: relatedArticles.map((a) => a.slug),
        durationMs: Date.now() - started,
      },
      { status: 200 },
    );
  } catch (e) {
    return NextResponse.json(
      {
        success: false,
        error: e instanceof Error ? e.message : String(e),
        durationMs: Date.now() - started,
      },
      { status: 200 },
    );
  }
}

export async function GET(req: NextRequest) {
  return handler(req);
}

export async function POST(req: NextRequest) {
  return handler(req);
}
