/**
 * POST/GET /api/cron/auto-article
 *
 * Cron endpoint: produce ONE auto-generated article draft by paraphrasing
 * a single existing published article that matches the chosen TargetKeyword.
 * Protected by `Authorization: Bearer ${CRON_SECRET}`.
 *
 * Spec (per editor request 2026-04-27):
 *   - 1 keyword → 1 source article → 1 paraphrased draft. Strictly 1:1.
 *   - The source MUST be a human-written published article whose topic
 *     matches the keyword. If none exists for the chosen keyword, skip.
 *   - The draft body is a faithful paraphrase of the source — same facts,
 *     same structure, but reworded. No invented claims.
 *   - The featured image (and category) from the source carry over so the
 *     draft looks complete.
 *   - The draft is flagged `isAutoGenerated=true` so editors can filter
 *     auto vs manual content in /panel/artikel.
 *
 * Flow:
 *   1. Check `SystemSetting.auto_article_enabled === "true"` — else skip
 *   2. Pick random active keyword (priority desc, random from top 10)
 *   3. Find ONE matching source article (with featuredImage, recent first)
 *   4. Call `callAI({feature: "article_draft", ...})` with paraphrase prompt
 *   5. Parse JSON; carry featuredImage + category from source
 *   6. Create Article status=DRAFT, isAutoGenerated=true, sourceArticleId set
 *   7. Update keyword.lastGeneratedAt + audit log
 *
 * All errors are trapped: endpoint always returns HTTP 200 with
 * `{success:false, error}` on failure so cron doesn't retry-spam.
 *
 * Recommend invocation: every 1 hour.
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { callAI } from "@/lib/ai-client";
import { slugify } from "@/lib/utils";
import { sanitizeHtml } from "@/lib/sanitize";
import { verifyCronSecret, errorResponse } from "@/lib/api-utils";
import { trackCron } from "@/lib/cron-tracker";
import { checkArticle } from "@/lib/ai-guardrail";
import { tryAdvisoryLock, releaseAdvisoryLock } from "@/lib/cron-lock";
import * as Sentry from "@sentry/nextjs";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

interface GeneratedArticle {
  title: string;
  excerpt: string;
  content: string;
  suggestedTags?: string[];
}

interface SourceArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string | null;
  content: string;          // already stripped to plain text + truncated
  rawContent: string;       // original HTML (for image extraction if needed)
  featuredImage: string | null;
  publishedAt: Date | null;
  categoryId: string;
  category: { name: string } | null;
}

/** Maximum number of paraphrased drafts allowed per source article. */
const MAX_DERIVATIVES_PER_SOURCE = 3;

/**
 * Return the IDs of source articles that have already been paraphrased
 * MAX_DERIVATIVES_PER_SOURCE times. These get excluded from future picks
 * so the same human-written article doesn't keep spawning AI rewrites.
 */
async function getExhaustedSourceIds(): Promise<string[]> {
  const grouped = await prisma.article.groupBy({
    by: ["sourceArticleId"],
    where: {
      isAutoGenerated: true,
      sourceArticleId: { not: null },
    },
    _count: { sourceArticleId: true },
    having: {
      sourceArticleId: { _count: { gte: MAX_DERIVATIVES_PER_SOURCE } },
    },
  });
  return grouped
    .map((g) => g.sourceArticleId)
    .filter((id): id is string => typeof id === "string");
}

/**
 * Find ONE published article whose topic matches the keyword.
 *
 * Matching strategy: title match preferred (signals topic), then excerpt,
 * then content. Recency tiebreak. We also prefer articles with a
 * featuredImage so the resulting draft looks complete out of the box.
 *
 * Hard rules:
 *   - Source MUST be human-written (`isAutoGenerated=false`) — never
 *     paraphrase an AI-generated article (avoids feedback loop).
 *   - Source MUST have produced fewer than `MAX_DERIVATIVES_PER_SOURCE`
 *     paraphrases so far. Once a source has spawned 3 drafts, it is
 *     exhausted and gets skipped.
 *
 * Returns null if nothing matches — the cron skips this run.
 */
async function findSingleSource(keyword: string): Promise<SourceArticle | null> {
  const MAX_CONTEXT_CHARS = 4_500; // roughly 700 words — enough to paraphrase faithfully

  const exhausted = await getExhaustedSourceIds();
  const baseWhere = {
    status: "PUBLISHED" as const,
    isAutoGenerated: false, // never paraphrase another auto-article
    ...(exhausted.length > 0 ? { id: { notIn: exhausted } } : {}),
  };

  // Try, in order: title match (with image) → title match → excerpt match → content match.
  // First hit wins. This biases toward articles whose primary topic IS the keyword.
  const orderedQueries = [
    {
      ...baseWhere,
      title: { contains: keyword, mode: "insensitive" as const },
      featuredImage: { not: null },
    },
    {
      ...baseWhere,
      title: { contains: keyword, mode: "insensitive" as const },
    },
    {
      ...baseWhere,
      excerpt: { contains: keyword, mode: "insensitive" as const },
      featuredImage: { not: null },
    },
    {
      ...baseWhere,
      excerpt: { contains: keyword, mode: "insensitive" as const },
    },
    {
      ...baseWhere,
      content: { contains: keyword, mode: "insensitive" as const },
      featuredImage: { not: null },
    },
    {
      ...baseWhere,
      content: { contains: keyword, mode: "insensitive" as const },
    },
  ];

  for (const where of orderedQueries) {
    const article = await prisma.article.findFirst({
      where,
      orderBy: [{ publishedAt: "desc" }, { viewCount: "desc" }],
      select: {
        id: true,
        slug: true,
        title: true,
        excerpt: true,
        content: true,
        featuredImage: true,
        publishedAt: true,
        categoryId: true,
        category: { select: { name: true } },
      },
    });
    if (article) {
      return {
        ...article,
        rawContent: article.content,
        content: stripHtml(article.content).slice(0, MAX_CONTEXT_CHARS),
      };
    }
  }
  return null;
}

function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  // Remove leading ```json / ```
  const fenced = trimmed.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  if (fenced) return fenced[1].trim();
  return trimmed;
}

function tryParseJson(raw: string): GeneratedArticle | null {
  try {
    const cleaned = stripCodeFence(raw);
    const parsed = JSON.parse(cleaned);
    if (
      parsed &&
      typeof parsed === "object" &&
      typeof parsed.title === "string" &&
      typeof parsed.content === "string"
    ) {
      return {
        title: parsed.title.trim(),
        excerpt:
          typeof parsed.excerpt === "string" ? parsed.excerpt.trim() : "",
        content: parsed.content.trim(),
        suggestedTags: Array.isArray(parsed.suggestedTags)
          ? parsed.suggestedTags
              .filter((t: unknown): t is string => typeof t === "string")
              .slice(0, 10)
          : [],
      };
    }
  } catch {
    // fall through
  }
  return null;
}

function fallbackParse(raw: string, keyword: string): GeneratedArticle {
  // Pull first non-empty line as title, rest as content.
  const lines = raw
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const title = lines[0]
    ? lines[0].replace(/^#+\s*/, "").slice(0, 120)
    : `Kabar Terkini: ${keyword}`;
  const body = lines.slice(1).join("\n\n") || raw.trim();
  const contentHtml = body
    .split(/\n{2,}/)
    .map((p) => `<p>${p.trim()}</p>`)
    .join("\n");
  return {
    title,
    excerpt: body.slice(0, 180).replace(/\s+\S*$/, ""),
    content: contentHtml || `<p>${raw.slice(0, 800)}</p>`,
    suggestedTags: [],
  };
}

async function uniqueSlug(base: string): Promise<string> {
  const root = slugify(base).slice(0, 90) || "artikel";
  const existing = await prisma.article.findUnique({
    where: { slug: root },
    select: { id: true },
  });
  if (!existing) return root;
  const suffix = Math.random().toString(36).slice(2, 8);
  return `${root}-${suffix}`;
}

// Read SystemSetting with default fallback. Empty string and missing rows
// both fall back to the default.
async function readSetting(key: string, fallback: string): Promise<string> {
  try {
    const row = await prisma.systemSetting.findUnique({ where: { key } });
    if (!row || !row.value) return fallback;
    return row.value;
  } catch {
    return fallback;
  }
}

async function writeSetting(key: string, value: string): Promise<void> {
  try {
    await prisma.systemSetting.upsert({
      where: { key },
      update: { value },
      create: { key, value },
    });
  } catch {
    /* swallow */
  }
}

// Generate ONE auto-article. Returns null on skip (with reason logged in
// the result); caller (the batch loop) treats null as "this slot didn't
// produce, try next". Errors that should abort the whole batch throw.
type GenerateResult =
  | { ok: true; articleId: string; slug: string; title: string; keyword: string; provider: string; tokens: number; sourceId: string }
  | { ok: false; reason: string; keyword?: string };

async function generateOne(): Promise<GenerateResult> {
  // Pick keyword
  const keywords = await prisma.targetKeyword.findMany({
    where: { isActive: true },
    orderBy: { priority: "desc" },
    take: 10,
  });
  if (keywords.length === 0) {
    return { ok: false, reason: "no-active-keywords" };
  }
  const kw = keywords[Math.floor(Math.random() * keywords.length)];

  // Find ONE source article whose topic matches the keyword.
  //    Strict 1:1 — if no source exists, skip (the cron should not invent
  //    facts about a topic we have no human-written reference for).
  const source = await findSingleSource(kw.keyword);
  if (!source) {
    return { ok: false, reason: "no-source-article-for-keyword", keyword: kw.keyword };
  }

  const sourceDate = source.publishedAt
    ? new Date(source.publishedAt).toLocaleDateString("id-ID", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : "";

  const userPrompt = `Tugas: tulis ulang (PARAFRASA) artikel berita berikut dalam Bahasa Indonesia jurnalistik. Bukan tulis baru, bukan sintesis — paraphrase artikel ini.

ARTIKEL SUMBER (judul / kategori / tanggal / isi):
JUDUL: ${source.title}
KATEGORI: ${source.category?.name ?? "Umum"}
TANGGAL: ${sourceDate}
${source.excerpt ? `RINGKASAN: ${source.excerpt}\n` : ""}ISI:
${source.content}

ATURAN PARAFRASA (WAJIB):
1. Pertahankan SEMUA fakta dari sumber — nama, jabatan, angka, tanggal, lokasi, kutipan langsung jangan diubah.
2. Reword setiap kalimat dengan struktur kata baru. Jangan menyalin kalimat persis.
3. Jangan menambah klaim baru, prediksi, atau fakta yang tidak ada di sumber.
4. Jangan menghapus poin penting. Pertahankan urutan kronologis / argumentasi sumber.
5. Panjang artikel paraphrase: ~80–110% panjang sumber. Body 400–800 kata, sesuai sumber.
6. Gaya bahasa: lead 5W+1H di paragraf pertama, gunakan paragraf pendek 2–4 kalimat, sertakan minimal 1 sub-heading <h2> kalau sumber punya struktur sectioned.
7. Judul baru: ringkasan inti, 50–80 karakter, BEDA dari judul sumber tapi tetap akurat menggambarkan topik.
8. Excerpt: 150–200 karakter, tarik fakta paling kuat dari paragraf pertama.

Keyword fokus: "${kw.keyword}"

Format output WAJIB JSON valid (tanpa teks lain, tanpa code-fence):
{
  "title": "judul paraphrase 50-80 karakter",
  "excerpt": "ringkasan 150-200 karakter",
  "content": "body HTML dengan <p>, <h2>, <blockquote> kalau sumber punya kutipan, <ul> kalau ada list",
  "suggestedTags": ["tag1", "tag2", "tag3"]
}`;

  let aiResult;
  try {
    aiResult = await callAI({
      feature: "article_draft",
      userPrompt,
      maxTokens: 2000,
      temperature: 0.7,
    });
  } catch (e) {
    return { ok: false, reason: `ai-failed: ${e instanceof Error ? e.message : String(e)}`, keyword: kw.keyword };
  }

  // Parse
  const parsed =
    tryParseJson(aiResult.text) ?? fallbackParse(aiResult.text, kw.keyword);

  // ── Guardrail: check for AI hallucinations ─────────────────────────────
  // Strip HTML from generated content for plain-text comparison.
  const generatedPlain = stripHtml(parsed.content);
  const guardrail = checkArticle(generatedPlain, source.content);

  if (guardrail.hasCritical) {
    // CRITICAL: fabricated direct quote detected — skip article entirely.
    const criticalDetails = guardrail.warnings
      .filter((w) => w.critical)
      .map((w) => w.detail)
      .join("; ");

    // Log to audit so editors can review
    try {
      const admin = await prisma.user.findFirst({
        where: { role: "SUPER_ADMIN" },
        orderBy: { createdAt: "asc" },
        select: { id: true },
      });
      if (admin) {
        await prisma.auditLog.create({
          data: {
            userId: admin.id,
            action: "CRON_AUTO_ARTICLE_GUARDRAIL_BLOCK",
            entity: "article",
            entityId: "N/A",
            detail: JSON.stringify({
              keyword: kw.keyword,
              sourceId: source.id,
              reason: "fabricated-quote",
              details: criticalDetails,
            }),
          },
        });
      }
    } catch { /* swallow */ }

    return {
      ok: false,
      reason: `guardrail-critical: ${criticalDetails.slice(0, 200)}`,
      keyword: kw.keyword,
    };
  }

  // SOFT warnings: save article but flag as UNVERIFIED + add review flag.
  const hasGuardrailWarnings = guardrail.warnings.length > 0;

  // Resolve author
  const admin = await prisma.user.findFirst({
    where: { role: "SUPER_ADMIN" },
    orderBy: { createdAt: "asc" },
    select: { id: true },
  });
  if (!admin) {
    return { ok: false, reason: "no-super-admin", keyword: kw.keyword };
  }

  // Category & featured image inherit from source.
  const categoryId = source.categoryId;
  const featuredImage = source.featuredImage;

  // Embed the featured image as the FIRST <img> in the content HTML so it
  // shows inline at the top of the rich-text editor (and the article body
  // on the public page). The featuredImage field is also kept for OG tags
  // and the news sitemap. extractFirstImageUrl in the article PUT keeps
  // the two in sync if the editor later reorders or replaces images.
  let bodyHtml = sanitizeHtml(parsed.content);
  if (featuredImage && !/<img[^>]*src=/i.test(bodyHtml)) {
    const altText = parsed.title.slice(0, 200).replace(/"/g, "&quot;");
    bodyHtml = `<p><img src="${featuredImage}" alt="${altText}" /></p>` + bodyHtml;
  }

  // Create article — sourceArticleId always set (we abort earlier if no source).
  const slug = await uniqueSlug(parsed.title);
  // Soft guardrail warnings: keep UNVERIFIED and add a review note.
  const verificationLabel = hasGuardrailWarnings ? "UNVERIFIED" : "UNVERIFIED";
  const reviewNote = hasGuardrailWarnings
    ? `[Guardrail] Kemungkinan data tidak cocok dengan sumber: ${guardrail.warnings.map((w) => w.detail).join("; ").slice(0, 800)}`
    : null;

  let article;
  try {
    article = await prisma.article.create({
      data: {
        title: parsed.title.slice(0, 250),
        slug,
        content: bodyHtml,
        excerpt: parsed.excerpt.slice(0, 500) || null,
        featuredImage,
        status: "DRAFT",
        verificationLabel,
        reviewNote,
        isAutoGenerated: true,
        sourceArticleId: source.id,
        authorId: admin.id,
        categoryId,
      },
      select: { id: true, slug: true, title: true },
    });
  } catch (e) {
    return { ok: false, reason: `db-create-failed: ${e instanceof Error ? e.message : String(e)}`, keyword: kw.keyword };
  }

  // Update keyword.lastGeneratedAt (best-effort)
  try {
    await prisma.targetKeyword.update({
      where: { id: kw.id },
      data: { lastGeneratedAt: new Date() },
    });
  } catch {
    /* swallow */
  }

  // Audit log (best-effort)
  try {
    await prisma.auditLog.create({
      data: {
        userId: admin.id,
        action: "CRON_AUTO_ARTICLE",
        entity: "article",
        entityId: article.id,
        detail: JSON.stringify({
          keyword: kw.keyword,
          provider: aiResult.provider,
          tokens: aiResult.totalTokens,
          sourceId: source.id,
          sourceSlug: source.slug,
          mode: "paraphrase",
          guardrailWarnings: guardrail.warnings.length,
          guardrailPass: guardrail.pass,
        }),
      },
    });
  } catch {
    /* swallow */
  }

  return {
    ok: true,
    articleId: article.id,
    slug: article.slug,
    title: article.title,
    keyword: kw.keyword,
    provider: aiResult.provider,
    tokens: aiResult.totalTokens,
    sourceId: source.id,
  };
}

// Convert a stored interval value (string) into a clamped minutes number.
// Allowed values: 5, 10, 15, 20, 30, 60. Anything else → 60.
function parseInterval(raw: string): number {
  const n = Number(raw);
  if ([5, 10, 15, 20, 30, 60].includes(n)) return n;
  return 60;
}

// Clamp batch size to [0, 3]. Editorial cap so a single cron tick never
// floods the queue with more than 3 paraphrased drafts. 0 means
// "throttle ok but produce nothing".
function parseBatch(raw: string): number {
  const n = Math.floor(Number(raw));
  if (Number.isNaN(n)) return 1;
  if (n < 0) return 0;
  if (n > 3) return 3;
  return n;
}

async function handler(req: NextRequest) {
  const started = Date.now();
  try {
    try { verifyCronSecret(req); } catch (e) { return errorResponse(e); }

    // 1. Advisory lock — prevent concurrent invocations from duplicating work.
    //    Acquire BEFORE the toggle/throttle checks so a concurrent request
    //    that already passed those gates doesn't race into generateOne().
    const LOCK_KEY = "cron:auto-article";
    const lockAcquired = await tryAdvisoryLock(LOCK_KEY);
    if (!lockAcquired) {
      return NextResponse.json(
        {
          success: false,
          skipped: true,
          reason: "ANOTHER_RUN_IN_PROGRESS",
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    try {

    // 2. Toggle check
    const enabledStr = await readSetting("auto_article_enabled", "false");
    if (enabledStr !== "true") {
      return NextResponse.json(
        { success: true, skipped: "disabled", durationMs: Date.now() - started },
        { status: 200 },
      );
    }

    // 3. Throttle check — settings drive how often we actually generate.
    //    The crontab fires the endpoint frequently (every 5 min); this gate
    //    enforces the user's configured cadence without touching crontab.
    const intervalMin = parseInterval(await readSetting("auto_article_interval_minutes", "60"));
    const batchSize = parseBatch(await readSetting("auto_article_batch_size", "1"));
    const lastRunIso = await readSetting("auto_article_last_run_at", "");
    const lastRunAt = lastRunIso ? new Date(lastRunIso) : null;
    const now = new Date();

    if (lastRunAt && !Number.isNaN(lastRunAt.getTime())) {
      const elapsedMin = (now.getTime() - lastRunAt.getTime()) / 60000;
      if (elapsedMin < intervalMin) {
        return NextResponse.json(
          {
            success: true,
            skipped: "throttled",
            intervalMinutes: intervalMin,
            elapsedMinutes: Math.round(elapsedMin * 10) / 10,
            nextRunIn: Math.round((intervalMin - elapsedMin) * 10) / 10,
            durationMs: Date.now() - started,
          },
          { status: 200 },
        );
      }
    }

    // 3. Update last_run_at FIRST so concurrent invocations from a flaky cron
    //    don't double-fire. Even if every generateOne below skips/fails, the
    //    next throttle window will only open after intervalMin from now.
    await writeSetting("auto_article_last_run_at", now.toISOString());

    if (batchSize === 0) {
      return NextResponse.json(
        {
          success: true,
          skipped: "batch-size-zero",
          intervalMinutes: intervalMin,
          batchSize: 0,
          durationMs: Date.now() - started,
        },
        { status: 200 },
      );
    }

    // 4. Generate batchSize articles. Continue past per-iteration skips/errors
    //    (no source for keyword, AI throttle, etc.) so a partial batch still
    //    produces something useful.
    const results: GenerateResult[] = [];
    for (let i = 0; i < batchSize; i++) {
      const r = await generateOne();
      results.push(r);
      // No artificial delay — AI provider already serialises calls.
    }

    const created = results.filter((r) => r.ok);
    const skipped = results.filter((r) => !r.ok);

    return NextResponse.json(
      {
        success: true,
        intervalMinutes: intervalMin,
        batchSize,
        created: created.length,
        skipped: skipped.length,
        articles: created.map((r) => r.ok ? { id: r.articleId, slug: r.slug, title: r.title, keyword: r.keyword } : null).filter(Boolean),
        skips: skipped.map((r) => !r.ok ? { reason: r.reason, keyword: r.keyword } : null).filter(Boolean),
        durationMs: Date.now() - started,
      },
      { status: 200 },
    );
    } finally {
      // Release lock regardless of success, error, or early return inside the
      // inner try so the next cron tick can acquire it normally.
      await releaseAdvisoryLock(LOCK_KEY);
    }
  } catch (e) {
    // Unexpected error — surface as 5xx so monitoring (UptimeRobot, Sentry)
    // flags an alert. Expected skips (disabled, throttled, lock-held) all
    // return 200 above and never reach here.
    Sentry.captureException(e, { tags: { cron: "auto-article" } });
    console.error("[cron auto-article] UNEXPECTED:", e);
    return NextResponse.json(
      {
        success: false,
        error: e instanceof Error ? e.message : String(e),
        durationMs: Date.now() - started,
      },
      { status: 500 },
    );
  }
}

export async function GET(req: NextRequest) {
  try {
    return await trackCron("auto-article", () => handler(req));
  } catch (e) {
    return errorResponse(e);
  }
}

export async function POST(req: NextRequest) {
  try {
    return await trackCron("auto-article", () => handler(req));
  } catch (e) {
    return errorResponse(e);
  }
}
