/**
 * Paraphrase a single ScrapedArticle into a Kartawarta DRAFT article.
 *
 * Strict 1:1: one source URL → one draft. The cron's listing pass walks
 * candidates and calls this for the first one not already in
 * `NewsSource.scrapedUrls`.
 *
 * Pipeline:
 *   1. AI paraphrase (callAI feature="article_draft"). When the source
 *      is English, the prompt asks for a Bahasa Indonesia translation
 *      + paraphrase in one pass.
 *   2. Resolve fields: title / excerpt / content / tags from AI output.
 *   3. Download hero image to /uploads (registered in Media library).
 *   4. Append a "Disarikan dari …" attribution footer.
 *   5. Insert Article row with status=DRAFT, isAutoGenerated=true,
 *      sourceArticleId remains null (source is external — we just
 *      record it in the audit log + content footer).
 */

import * as cheerio from "cheerio";
import { prisma } from "@/lib/prisma";
import { callAI } from "@/lib/ai-client";
import { sanitizeHtml, cleanAIShortText, cleanAILongText } from "@/lib/sanitize";
import { slugify } from "@/lib/utils";
import { downloadImageToUploads } from "./download-image";
import type { ScrapedArticle } from "./types";

const MAX_BODY_IMAGES = 5;

/**
 * Pull every `<img>` URL from the source body in document order, dedup,
 * resolve relative URLs against `baseUrl`, and skip the hero image so we
 * don't duplicate what's already used as featuredImage.
 */
/**
 * Reject URLs that look like logos, icons, avatars, or chrome — i.e.
 * NOT body images. We can't inspect dimensions from a URL alone, so we
 * filter on filename + path tokens that are reliably non-content.
 */
const NON_BODY_IMAGE_PATTERNS = [
  /logo/i,
  /favicon/i,
  /\bicon[s]?\b/i,
  /watermark/i,
  /placeholder/i,
  /spinner/i,
  /loading/i,
  /\bavatar\b/i,
  /\bsprite\b/i,
  /\bbutton\b/i,
  /\bbadge\b/i,
  /\.svg(\?|$)/i,
  /\bblank\b/i,
];

function looksLikeBodyImage(url: string): boolean {
  return !NON_BODY_IMAGE_PATTERNS.some((re) => re.test(url));
}

function extractBodyImageUrls(
  html: string,
  baseUrl: string,
  excludeHeroUrl?: string,
): string[] {
  const $ = cheerio.load(html);
  const seen = new Set<string>();
  const out: string[] = [];
  $("img").each((_, el) => {
    const $img = $(el);
    const raw =
      $img.attr("src") ||
      $img.attr("data-src") ||
      $img.attr("data-lazy-src") ||
      $img.attr("data-original");
    if (!raw) return;
    let abs: string;
    try {
      abs = new URL(raw, baseUrl).toString();
    } catch {
      return;
    }
    if (!/^https?:\/\//i.test(abs)) return;
    if (excludeHeroUrl && abs === excludeHeroUrl) return;
    if (!looksLikeBodyImage(abs)) return;
    if (seen.has(abs)) return;
    seen.add(abs);
    out.push(abs);
  });
  return out.slice(0, MAX_BODY_IMAGES);
}

/**
 * Inject `<figure><img/></figure>` markers into the AI-paraphrased body
 * at evenly-spaced paragraph boundaries. We split on `</p>` so images
 * always land between full paragraphs, never inside one.
 *
 * Layout: image #1 lands after the first paragraph (right under the
 * lead), the rest are spaced through the body.
 */
function injectImagesIntoBody(
  bodyHtml: string,
  imageUrls: string[],
  altText: string,
): string {
  if (imageUrls.length === 0) return bodyHtml;

  // Split on closing </p> so we keep paragraph integrity.
  const parts = bodyHtml.split(/(<\/p>)/i);
  const paragraphCloses: number[] = [];
  parts.forEach((seg, i) => {
    if (/<\/p>/i.test(seg)) paragraphCloses.push(i);
  });

  if (paragraphCloses.length === 0) {
    // Fallback: just append figures at the end.
    const figures = imageUrls
      .map(
        (url) =>
          `<figure><img src="${url}" alt="${escapeAttr(altText)}" /></figure>`,
      )
      .join("\n");
    return `${bodyHtml}\n${figures}`;
  }

  // Pick insertion indexes: spread over paragraph closes, capped by image count.
  // E.g. 6 paragraphs + 3 images → indexes [1, 3, 5] (after p1, p3, p5).
  const insertAt: number[] = [];
  const N = paragraphCloses.length;
  const M = Math.min(imageUrls.length, N);
  for (let k = 1; k <= M; k++) {
    const pos = Math.floor((k * N) / (M + 1));
    insertAt.push(paragraphCloses[pos]);
  }
  const insertSet = new Map<number, string>();
  insertAt.forEach((idx, k) => {
    const url = imageUrls[k];
    insertSet.set(
      idx,
      `<figure><img src="${url}" alt="${escapeAttr(altText)}" /></figure>`,
    );
  });

  // Always put image #0 right after the first paragraph (lead) when there's
  // at least one. This makes the article feel illustrated from the start.
  if (imageUrls.length > 0) {
    const firstClose = paragraphCloses[0];
    insertSet.set(
      firstClose,
      `<figure><img src="${imageUrls[0]}" alt="${escapeAttr(altText)}" /></figure>`,
    );
  }

  // Re-assemble.
  const rebuilt: string[] = [];
  parts.forEach((seg, i) => {
    rebuilt.push(seg);
    if (insertSet.has(i)) rebuilt.push(insertSet.get(i)!);
  });
  return rebuilt.join("");
}

function escapeAttr(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

interface AiParaphrase {
  title: string;
  excerpt: string;
  content: string;
  suggestedTags: string[];
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  if (fenced) return fenced[1].trim();
  return trimmed;
}

function tryParseAi(raw: string): AiParaphrase | null {
  try {
    const cleaned = stripCodeFence(raw);
    const parsed = JSON.parse(cleaned);
    if (
      parsed &&
      typeof parsed.title === "string" &&
      typeof parsed.content === "string"
    ) {
      const cleanedTitle = cleanAIShortText(parsed.title) || parsed.title.trim();
      const cleanedExcerpt =
        typeof parsed.excerpt === "string"
          ? cleanAIShortText(parsed.excerpt) || parsed.excerpt.trim()
          : "";
      const cleanedContent = cleanAILongText(parsed.content) || parsed.content.trim();
      return {
        title: cleanedTitle,
        excerpt: cleanedExcerpt,
        content: cleanedContent,
        suggestedTags: Array.isArray(parsed.suggestedTags)
          ? parsed.suggestedTags
              .filter((t: unknown): t is string => typeof t === "string")
              .slice(0, 8)
          : [],
      };
    }
  } catch {
    // fall through
  }
  return null;
}

async function uniqueSlug(base: string): Promise<string> {
  const root = slugify(base).slice(0, 90) || "artikel";
  const existing = await prisma.article.findUnique({
    where: { slug: root },
    select: { id: true },
  });
  if (!existing) return root;
  const suffix = Math.random().toString(36).slice(2, 8);
  return `${root}-${suffix}`;
}

function buildAttribution(
  sourceUrl: string,
  sourceName: string,
  originalTitle: string,
): string {
  const safeTitle = originalTitle.replace(/[<>"]/g, "");
  return `<p class="text-sm italic text-txt-muted mt-8 pt-4 border-t border-border">Disarikan dari rilis <a href="${sourceUrl}" target="_blank" rel="nofollow noopener">${sourceName} — "${safeTitle}"</a>. Versi Kartawarta ditulis ulang oleh tim editorial dengan dukungan AI; fakta dan kutipan tetap mengacu ke publikasi asli.</p>`;
}

export interface ParaphraseInput {
  /** The scraped upstream article. */
  source: ScrapedArticle;
  /** Display name of the source (e.g. "Bank BJB"). */
  sourceName: string;
  /** Owner of the resulting draft. */
  authorId: string;
  authorName: string;
  /** Category the draft will land in. */
  categoryId: string;
  /** Default tags from the NewsSource. */
  defaultTags?: string[];
  /** Whether to download the hero image. Default true. */
  downloadImage?: boolean;
}

export interface ParaphraseResult {
  articleId: string;
  slug: string;
  title: string;
  /** Tokens reported by callAI(). */
  tokens: number;
  /** AI provider used. */
  provider: string;
  /** Local URL of the downloaded hero image, if any. */
  featuredImage?: string;
  /** Detected language of the upstream source. */
  sourceLang?: string;
}

export async function paraphraseAndCreateDraft(
  input: ParaphraseInput,
): Promise<ParaphraseResult> {
  const { source, sourceName, authorId, categoryId, defaultTags = [] } = input;
  const downloadImage = input.downloadImage ?? true;

  const isEnglish = source.lang === "en";
  const langInstruction = isEnglish
    ? `Sumber dalam Bahasa Inggris — terjemahkan SEKALIGUS parafrase ke Bahasa Indonesia jurnalistik yang baik dan benar.`
    : `Sumber dalam Bahasa Indonesia — parafrase ulang dengan kalimat yang berbeda namun mempertahankan fakta.`;

  const userPrompt = `Anda menulis ulang sebuah artikel berita untuk Kartawarta (media berita digital Bandung dengan fokus bisnis, ekonomi, pemerintahan, dan hukum, plus topik general lain) dengan gaya jurnalistik objektif.

${langInstruction}

ATURAN WAJIB:
- JANGAN menjiplak kalimat sumber. Susun ulang sepenuhnya.
- JANGAN tambahkan klaim yang tidak ada di sumber.
- Pertahankan SEMUA angka, nama, jabatan, dan kutipan langsung dari sumber dengan akurat.
- Lead paragraf wajib menjawab 5W+1H.
- Panjang body: 500-800 kata.
- Hasil HTML rapi: <p>, <h2>, <ul>, <strong> seperlunya.

JUDUL SUMBER: "${source.title}"

ISI SUMBER (${source.wordCount} kata):
"""
${source.contentHtml.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").slice(0, 6_000)}
"""

Format output WAJIB JSON valid (tanpa teks lain di luar JSON):
{
  "title": "judul Kartawarta yang fresh & menarik (50-80 karakter, hindari clickbait)",
  "excerpt": "ringkasan 130-160 karakter dalam Bahasa Indonesia",
  "content": "body artikel HTML 500-800 kata, lead 5W+1H, paragraf rapi",
  "suggestedTags": ["tag1", "tag2", "tag3", "tag4", "tag5"]
}`;

  const ai = await callAI({
    feature: "article_draft",
    userPrompt,
    maxTokens: 2_500,
    temperature: 0.65,
  });

  const parsed = tryParseAi(ai.text);
  if (!parsed) {
    throw new Error(
      `AI did not return parseable JSON for ${source.url}. First 200 chars: ${ai.text.slice(0, 200)}`,
    );
  }

  // Image: download hero + body images to /uploads if requested.
  let featuredImage: string | undefined;
  if (downloadImage && source.heroImageUrl) {
    try {
      const dl = await downloadImageToUploads(source.heroImageUrl, {
        title: parsed.title.slice(0, 200),
        caption: parsed.excerpt || source.excerpt,
        credit: sourceName,
        uploadedBy: authorId,
        uploaderName: input.authorName,
      });
      featuredImage = dl.url;
    } catch {
      // Non-fatal — draft still gets created without an image.
    }
  } else if (source.heroImageUrl) {
    featuredImage = source.heroImageUrl;
  }

  // Pull body images from the upstream article and download each to
  // /uploads. We then inject them into the AI-paraphrased body so the
  // resulting draft is fully illustrated, not just hero + walls of text.
  const localBodyImageUrls: string[] = [];
  if (downloadImage) {
    const upstreamBodyImageUrls = extractBodyImageUrls(
      source.contentHtml,
      source.url,
      source.heroImageUrl,
    );
    for (const upstreamUrl of upstreamBodyImageUrls) {
      try {
        const dl = await downloadImageToUploads(upstreamUrl, {
          title: parsed.title.slice(0, 200),
          caption: parsed.excerpt || source.excerpt,
          credit: sourceName,
          uploadedBy: authorId,
          uploaderName: input.authorName,
        });
        localBodyImageUrls.push(dl.url);
      } catch {
        // Skip individual failures — still want the rest of the
        // images to make it through.
      }
    }
  }

  const bodyWithImages = injectImagesIntoBody(
    parsed.content,
    localBodyImageUrls,
    parsed.title,
  );
  const finalContent = sanitizeHtml(bodyWithImages);

  const slug = await uniqueSlug(parsed.title);

  // Tags: union of AI-suggested + defaults (capped 8)
  const allTagNames = Array.from(
    new Set(
      [...parsed.suggestedTags, ...defaultTags]
        .map((t) => t.trim())
        .filter((t) => t.length > 0 && t.length <= 40),
    ),
  ).slice(0, 8);

  // Upsert tags + collect IDs
  const tagConnections: { id: string }[] = [];
  if (allTagNames.length > 0) {
    await Promise.all(
      allTagNames.map((name) =>
        prisma.tag.upsert({
          where: { slug: slugify(name) },
          update: {},
          create: { name, slug: slugify(name) },
        }),
      ),
    );
    const tags = await prisma.tag.findMany({
      where: { slug: { in: allTagNames.map((n) => slugify(n)) } },
      select: { id: true },
    });
    tagConnections.push(...tags.map((t) => ({ id: t.id })));
  }

  const article = await prisma.article.create({
    data: {
      title: parsed.title.slice(0, 250),
      slug,
      content: finalContent,
      excerpt:
        parsed.excerpt.slice(0, 500) || source.excerpt.slice(0, 500) || null,
      status: "DRAFT",
      isAutoGenerated: true,
      sourceArticleId: null,
      featuredImage: featuredImage || null,
      authorId,
      categoryId,
      tags:
        tagConnections.length > 0 ? { connect: tagConnections } : undefined,
    },
    select: { id: true, slug: true, title: true },
  });

  return {
    articleId: article.id,
    slug: article.slug,
    title: article.title,
    tokens: ai.totalTokens,
    provider: ai.provider,
    featuredImage,
    sourceLang: source.lang,
  };
}
