/**
 * Paraphrase a single ScrapedArticle into a Kartawarta DRAFT article.
 *
 * Strict 1:1: one source URL → one draft. The cron's listing pass walks
 * candidates and calls this for the first one not already in
 * `NewsSource.scrapedUrls`.
 *
 * Pipeline:
 *   1. AI paraphrase (callAI feature="article_draft"). When the source
 *      is English, the prompt asks for a Bahasa Indonesia translation
 *      + paraphrase in one pass.
 *   2. Resolve fields: title / excerpt / content / tags from AI output.
 *   3. Download hero image to /uploads (registered in Media library).
 *   4. Append a "Disarikan dari …" attribution footer.
 *   5. Insert Article row with status=DRAFT, isAutoGenerated=true,
 *      sourceArticleId remains null (source is external — we just
 *      record it in the audit log + content footer).
 */

import { prisma } from "@/lib/prisma";
import { callAI } from "@/lib/ai-client";
import { sanitizeHtml } from "@/lib/sanitize";
import { slugify } from "@/lib/utils";
import { downloadImageToUploads } from "./download-image";
import type { ScrapedArticle } from "./types";

interface AiParaphrase {
  title: string;
  excerpt: string;
  content: string;
  suggestedTags: string[];
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  if (fenced) return fenced[1].trim();
  return trimmed;
}

function tryParseAi(raw: string): AiParaphrase | null {
  try {
    const cleaned = stripCodeFence(raw);
    const parsed = JSON.parse(cleaned);
    if (
      parsed &&
      typeof parsed.title === "string" &&
      typeof parsed.content === "string"
    ) {
      return {
        title: parsed.title.trim(),
        excerpt:
          typeof parsed.excerpt === "string" ? parsed.excerpt.trim() : "",
        content: parsed.content.trim(),
        suggestedTags: Array.isArray(parsed.suggestedTags)
          ? parsed.suggestedTags
              .filter((t: unknown): t is string => typeof t === "string")
              .slice(0, 8)
          : [],
      };
    }
  } catch {
    // fall through
  }
  return null;
}

async function uniqueSlug(base: string): Promise<string> {
  const root = slugify(base).slice(0, 90) || "artikel";
  const existing = await prisma.article.findUnique({
    where: { slug: root },
    select: { id: true },
  });
  if (!existing) return root;
  const suffix = Math.random().toString(36).slice(2, 8);
  return `${root}-${suffix}`;
}

function buildAttribution(
  sourceUrl: string,
  sourceName: string,
  originalTitle: string,
): string {
  const safeTitle = originalTitle.replace(/[<>"]/g, "");
  return `<p class="text-sm italic text-txt-muted mt-8 pt-4 border-t border-border">Disarikan dari rilis <a href="${sourceUrl}" target="_blank" rel="nofollow noopener">${sourceName} — "${safeTitle}"</a>. Versi Kartawarta ditulis ulang oleh tim editorial dengan dukungan AI; fakta dan kutipan tetap mengacu ke publikasi asli.</p>`;
}

export interface ParaphraseInput {
  /** The scraped upstream article. */
  source: ScrapedArticle;
  /** Display name of the source (e.g. "Bank BJB"). */
  sourceName: string;
  /** Owner of the resulting draft. */
  authorId: string;
  authorName: string;
  /** Category the draft will land in. */
  categoryId: string;
  /** Default tags from the NewsSource. */
  defaultTags?: string[];
  /** Whether to download the hero image. Default true. */
  downloadImage?: boolean;
}

export interface ParaphraseResult {
  articleId: string;
  slug: string;
  title: string;
  /** Tokens reported by callAI(). */
  tokens: number;
  /** AI provider used. */
  provider: string;
  /** Local URL of the downloaded hero image, if any. */
  featuredImage?: string;
  /** Detected language of the upstream source. */
  sourceLang?: string;
}

export async function paraphraseAndCreateDraft(
  input: ParaphraseInput,
): Promise<ParaphraseResult> {
  const { source, sourceName, authorId, categoryId, defaultTags = [] } = input;
  const downloadImage = input.downloadImage ?? true;

  const isEnglish = source.lang === "en";
  const langInstruction = isEnglish
    ? `Sumber dalam Bahasa Inggris — terjemahkan SEKALIGUS parafrase ke Bahasa Indonesia jurnalistik yang baik dan benar.`
    : `Sumber dalam Bahasa Indonesia — parafrase ulang dengan kalimat yang berbeda namun mempertahankan fakta.`;

  const userPrompt = `Anda menulis ulang sebuah artikel berita untuk Kartawarta (media hukum digital Bandung) dengan gaya jurnalistik objektif.

${langInstruction}

ATURAN WAJIB:
- JANGAN menjiplak kalimat sumber. Susun ulang sepenuhnya.
- JANGAN tambahkan klaim yang tidak ada di sumber.
- Pertahankan SEMUA angka, nama, jabatan, dan kutipan langsung dari sumber dengan akurat.
- Lead paragraf wajib menjawab 5W+1H.
- Panjang body: 500-800 kata.
- Hasil HTML rapi: <p>, <h2>, <ul>, <strong> seperlunya.

JUDUL SUMBER: "${source.title}"

ISI SUMBER (${source.wordCount} kata):
"""
${source.contentHtml.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").slice(0, 6_000)}
"""

Format output WAJIB JSON valid (tanpa teks lain di luar JSON):
{
  "title": "judul Kartawarta yang fresh & menarik (50-80 karakter, hindari clickbait)",
  "excerpt": "ringkasan 130-160 karakter dalam Bahasa Indonesia",
  "content": "body artikel HTML 500-800 kata, lead 5W+1H, paragraf rapi",
  "suggestedTags": ["tag1", "tag2", "tag3", "tag4", "tag5"]
}`;

  const ai = await callAI({
    feature: "article_draft",
    userPrompt,
    maxTokens: 2_500,
    temperature: 0.65,
  });

  const parsed = tryParseAi(ai.text);
  if (!parsed) {
    throw new Error(
      `AI did not return parseable JSON for ${source.url}. First 200 chars: ${ai.text.slice(0, 200)}`,
    );
  }

  // Image: download to /uploads if requested + URL exists.
  let featuredImage: string | undefined;
  if (downloadImage && source.heroImageUrl) {
    try {
      const dl = await downloadImageToUploads(source.heroImageUrl, {
        title: parsed.title.slice(0, 200),
        caption: parsed.excerpt || source.excerpt,
        credit: sourceName,
        uploadedBy: authorId,
        uploaderName: input.authorName,
      });
      featuredImage = dl.url;
    } catch {
      // Non-fatal — draft still gets created without an image.
    }
  } else if (source.heroImageUrl) {
    featuredImage = source.heroImageUrl;
  }

  // Attribution footer
  // Attribution footer removed per editor request 2026-04-28 — drafts now
  // ship clean HTML. Source URL is preserved on the NewsSource scrapedUrls
  // dedup list and in audit logs if attribution is later needed.
  const finalContent = sanitizeHtml(parsed.content);

  const slug = await uniqueSlug(parsed.title);

  // Tags: union of AI-suggested + defaults (capped 8)
  const allTagNames = Array.from(
    new Set(
      [...parsed.suggestedTags, ...defaultTags]
        .map((t) => t.trim())
        .filter((t) => t.length > 0 && t.length <= 40),
    ),
  ).slice(0, 8);

  // Upsert tags + collect IDs
  const tagConnections: { id: string }[] = [];
  if (allTagNames.length > 0) {
    await Promise.all(
      allTagNames.map((name) =>
        prisma.tag.upsert({
          where: { slug: slugify(name) },
          update: {},
          create: { name, slug: slugify(name) },
        }),
      ),
    );
    const tags = await prisma.tag.findMany({
      where: { slug: { in: allTagNames.map((n) => slugify(n)) } },
      select: { id: true },
    });
    tagConnections.push(...tags.map((t) => ({ id: t.id })));
  }

  const article = await prisma.article.create({
    data: {
      title: parsed.title.slice(0, 250),
      slug,
      content: finalContent,
      excerpt:
        parsed.excerpt.slice(0, 500) || source.excerpt.slice(0, 500) || null,
      status: "DRAFT",
      isAutoGenerated: true,
      sourceArticleId: null,
      featuredImage: featuredImage || null,
      authorId,
      categoryId,
      tags:
        tagConnections.length > 0 ? { connect: tagConnections } : undefined,
    },
    select: { id: true, slug: true, title: true },
  });

  return {
    articleId: article.id,
    slug: article.slug,
    title: article.title,
    tokens: ai.totalTokens,
    provider: ai.provider,
    featuredImage,
    sourceLang: source.lang,
  };
}
