/**
 * POST /api/admin/fix-photo-credits
 *
 * One-time (re-runnable) backfill that repairs the photo credit on existing
 * SCRAPER articles. The scraper used to credit photos with the configured
 * NewsSource.name; several sources were named "Kartawarta", so scraped
 * articles ended up crediting our own site instead of the website the photo
 * came from.
 *
 * For each scraper article (isAutoGenerated=true, sourceArticleId=null) we
 * derive the real publisher from the stored upstream URL's domain (e.g.
 * https://www.bola.com/... → "Bola") and:
 *   - rewrite the baked-in "Foto: Kartawarta" / "Sumber: Kartawarta" credits
 *     and the attribution footer inside Article.content,
 *   - fix Media.credit for the featured + body images,
 *   - fix the Source.name rows.
 *
 * Body: `{ "apply": true }` to write changes; omit / `false` for a dry-run
 * preview (no writes). Idempotent — re-running only touches credits that
 * still say "Kartawarta".
 *
 * SUPER_ADMIN only.
 */

import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import {
  requireRole,
  successResponse,
  errorResponse,
  logAudit,
} from "@/lib/api-utils";
import {
  sourceLabelFromUrl,
  rewriteCreditsInContent,
  footerSourceHref,
  uploadUrlsInContent,
} from "@/lib/scraper/source-label";

export const dynamic = "force-dynamic";
export const maxDuration = 120;

const BodySchema = z
  .object({ apply: z.boolean().optional() })
  .optional()
  .default({});

export async function POST(req: NextRequest) {
  try {
    const session = await requireRole(["SUPER_ADMIN"]);

    let parsed: { apply?: boolean } = {};
    try {
      parsed = BodySchema.parse(await req.json());
    } catch {
      // Empty/invalid body → dry-run.
    }
    const apply = parsed.apply === true;

    const articles = await prisma.article.findMany({
      where: { isAutoGenerated: true, sourceArticleId: null },
      select: {
        id: true,
        slug: true,
        content: true,
        featuredImage: true,
        sources: { select: { url: true, name: true }, take: 1 },
      },
    });

    let fixed = 0;
    let skipped = 0;
    const samples: Array<{ slug: string; to: string }> = [];
    const skippedSamples: Array<{ slug: string; reason: string }> = [];

    for (const a of articles) {
      // Real publisher: prefer the source row's URL, fall back to the
      // attribution footer link inside the content.
      const label =
        sourceLabelFromUrl(a.sources[0]?.url) ||
        sourceLabelFromUrl(footerSourceHref(a.content));

      if (!label) {
        skipped++;
        if (skippedSamples.length < 12) {
          skippedSamples.push({ slug: a.slug, reason: "URL sumber tidak ditemukan" });
        }
        continue;
      }

      const newContent = rewriteCreditsInContent(a.content, label);
      const contentChanged = newContent !== a.content;
      const imageUrls = [
        ...(a.featuredImage ? [a.featuredImage] : []),
        ...uploadUrlsInContent(a.content),
      ];

      let didFix = contentChanged;

      if (apply) {
        if (contentChanged) {
          await prisma.article.update({
            where: { id: a.id },
            data: { content: newContent },
          });
        }
        if (imageUrls.length > 0) {
          const mediaRes = await prisma.media.updateMany({
            where: {
              url: { in: imageUrls },
              OR: [
                { credit: null },
                { credit: "" },
                { credit: { contains: "kartawarta", mode: "insensitive" } },
              ],
            },
            data: { credit: label },
          });
          if (mediaRes.count > 0) didFix = true;
        }
        const srcRes = await prisma.source.updateMany({
          where: {
            articleId: a.id,
            name: { contains: "kartawarta", mode: "insensitive" },
          },
          data: { name: label },
        });
        if (srcRes.count > 0) didFix = true;
      } else {
        // Dry-run proxy: an article counts as fixable if its content changes
        // or it has images whose credit we'd correct.
        didFix = contentChanged || imageUrls.length > 0;
      }

      if (didFix) {
        fixed++;
        if (samples.length < 12) samples.push({ slug: a.slug, to: label });
      } else {
        skipped++;
        if (skippedSamples.length < 12) {
          skippedSamples.push({ slug: a.slug, reason: "sudah benar" });
        }
      }
    }

    await logAudit(
      session.user.id,
      apply ? "FIX_PHOTO_CREDITS_APPLY" : "FIX_PHOTO_CREDITS_DRYRUN",
      "article",
      "bulk",
      `scanned=${articles.length} fixed=${fixed} skipped=${skipped} apply=${apply}`,
    );

    return successResponse({
      applied: apply,
      scanned: articles.length,
      fixed,
      skipped,
      samples,
      skippedSamples,
    });
  } catch (error) {
    return errorResponse(error);
  }
}
