/**
 * /api/admin/fix-photo-credits   (SUPER_ADMIN only)
 *
 * Repairs the photo credit on existing SCRAPER articles
 * (isAutoGenerated=true, sourceArticleId=null) that still credit "Kartawarta"
 * — our own site — instead of the website the photo came from.
 *
 * The real publisher is recovered per-article via a fallback chain, because
 * older scraped articles don't all store their upstream URL:
 *   1. Source row URL          (articles scraped after 2026-05-29)
 *   2. "Disarikan dari" footer  (same era)
 *   3. Audit log of a cherry-pick "scrape one" (records articleId + url)
 *   4. The News Source feeding the article's CATEGORY (its listingUrl domain)
 *      — the catch-all for the bulk/cron-scraped backlog whose URL is lost.
 *
 * POST `{ "apply": true }` writes; omit/`false` is a dry-run preview.
 *   Fixes: Article.content credit text, Media.credit (featured + body),
 *   and Source.name. Idempotent — only touches credits still saying Kartawarta.
 *
 * GET → a plain-text diagnostic (sources, per-category counts, samples) to
 * eyeball what the backfill can/can't recover.
 */

import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import {
  requireRole,
  successResponse,
  errorResponse,
  logAudit,
} from "@/lib/api-utils";
import {
  sourceLabelFromUrl,
  rewriteCreditsInContent,
  footerSourceHref,
  uploadUrlsInContent,
} from "@/lib/scraper/source-label";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SCRAPER_WHERE = {
  isAutoGenerated: true,
  sourceArticleId: null,
} as const;

interface RecoveryContext {
  /** categoryId → { label, sourceName } derived from the News Source. */
  categoryLabel: Map<string, { label: string; sourceName: string }>;
  /** articleId → upstream url, recovered from "scrape one" audit logs. */
  auditUrl: Map<string, string>;
  /** categoryId → category name, for human-readable reporting. */
  categoryName: Map<string, string>;
}

async function buildContext(): Promise<RecoveryContext> {
  const [sources, audits, categories] = await Promise.all([
    prisma.newsSource.findMany({
      select: {
        name: true,
        listingUrl: true,
        categoryId: true,
        isActive: true,
        priority: true,
        totalScraped: true,
      },
    }),
    prisma.auditLog.findMany({
      where: { action: "NEWS_SOURCE_SCRAPE_ONE" },
      select: { detail: true },
    }),
    prisma.category.findMany({ select: { id: true, name: true } }),
  ]);

  // Best News Source per category: active first, then priority, then volume.
  const grouped = new Map<string, typeof sources>();
  for (const s of sources) {
    if (!s.categoryId) continue;
    const list = grouped.get(s.categoryId) ?? [];
    list.push(s);
    grouped.set(s.categoryId, list);
  }
  const categoryLabel = new Map<string, { label: string; sourceName: string }>();
  for (const [categoryId, list] of grouped) {
    list.sort(
      (a, b) =>
        Number(b.isActive) - Number(a.isActive) ||
        b.priority - a.priority ||
        b.totalScraped - a.totalScraped,
    );
    const best = list[0];
    const label = sourceLabelFromUrl(best.listingUrl);
    if (label) categoryLabel.set(categoryId, { label, sourceName: best.name });
  }

  const auditUrl = new Map<string, string>();
  for (const a of audits) {
    if (!a.detail) continue;
    try {
      const d = JSON.parse(a.detail) as { articleId?: string; url?: string };
      if (d.articleId && d.url && !auditUrl.has(d.articleId)) {
        auditUrl.set(d.articleId, d.url);
      }
    } catch {
      // ignore malformed audit detail
    }
  }

  const categoryName = new Map(categories.map((c) => [c.id, c.name]));
  return { categoryLabel, auditUrl, categoryName };
}

type Method = "source" | "footer" | "audit" | "category";

function recover(
  a: { id: string; content: string; categoryId: string; sources: { url: string | null }[] },
  ctx: RecoveryContext,
): { label: string; method: Method } | null {
  const fromSource = sourceLabelFromUrl(a.sources[0]?.url);
  if (fromSource) return { label: fromSource, method: "source" };

  const fromFooter = sourceLabelFromUrl(footerSourceHref(a.content));
  if (fromFooter) return { label: fromFooter, method: "footer" };

  const fromAudit = sourceLabelFromUrl(ctx.auditUrl.get(a.id));
  if (fromAudit) return { label: fromAudit, method: "audit" };

  const fromCategory = ctx.categoryLabel.get(a.categoryId);
  if (fromCategory) return { label: fromCategory.label, method: "category" };

  return null;
}

export async function POST(req: NextRequest) {
  try {
    const session = await requireRole(["SUPER_ADMIN"]);

    let body: { apply?: boolean } = {};
    try {
      body = z.object({ apply: z.boolean().optional() }).parse(await req.json());
    } catch {
      // empty/invalid → dry-run
    }
    const apply = body.apply === true;

    const ctx = await buildContext();
    const articles = await prisma.article.findMany({
      where: SCRAPER_WHERE,
      select: {
        id: true,
        slug: true,
        content: true,
        categoryId: true,
        featuredImage: true,
        sources: { select: { url: true }, take: 1 },
      },
    });

    let fixed = 0;
    let skipped = 0;
    const byMethod: Record<Method, number> = { source: 0, footer: 0, audit: 0, category: 0 };
    // categoryId → { label, count } for the human-readable plan.
    const planByCategory = new Map<string, { label: string; count: number }>();
    const samples: Array<{ slug: string; to: string; via: Method }> = [];
    const skippedSamples: Array<{ slug: string; reason: string }> = [];

    for (const a of articles) {
      const rec = recover(a, ctx);
      if (!rec) {
        skipped++;
        if (skippedSamples.length < 12) {
          skippedSamples.push({ slug: a.slug, reason: "sumber tidak diketahui" });
        }
        continue;
      }
      const { label, method } = rec;

      if (method === "category") {
        const entry = planByCategory.get(a.categoryId) ?? { label, count: 0 };
        entry.count++;
        planByCategory.set(a.categoryId, entry);
      }

      const newContent = rewriteCreditsInContent(a.content, label);
      const contentChanged = newContent !== a.content;
      const imageUrls = [
        ...(a.featuredImage ? [a.featuredImage] : []),
        ...uploadUrlsInContent(a.content),
      ];

      if (apply) {
        if (contentChanged) {
          await prisma.article.update({
            where: { id: a.id },
            data: { content: newContent },
          });
        }
        if (imageUrls.length > 0) {
          await prisma.media.updateMany({
            where: {
              url: { in: imageUrls },
              OR: [
                { credit: null },
                { credit: "" },
                { credit: { contains: "kartawarta", mode: "insensitive" } },
              ],
            },
            data: { credit: label },
          });
        }
        await prisma.source.updateMany({
          where: {
            articleId: a.id,
            name: { contains: "kartawarta", mode: "insensitive" },
          },
          data: { name: label },
        });
      }

      fixed++;
      byMethod[method]++;
      if (samples.length < 12) samples.push({ slug: a.slug, to: label, via: method });
    }

    const plan = Array.from(planByCategory.entries())
      .map(([categoryId, v]) => ({
        category: ctx.categoryName.get(categoryId) ?? categoryId,
        source: v.label,
        count: v.count,
      }))
      .sort((x, y) => y.count - x.count);

    await logAudit(
      session.user.id,
      apply ? "FIX_PHOTO_CREDITS_APPLY" : "FIX_PHOTO_CREDITS_DRYRUN",
      "article",
      "bulk",
      `scanned=${articles.length} fixed=${fixed} skipped=${skipped} apply=${apply} byMethod=${JSON.stringify(byMethod)}`,
    );

    return successResponse({
      applied: apply,
      scanned: articles.length,
      fixed,
      skipped,
      byMethod,
      plan,
      samples,
      skippedSamples,
    });
  } catch (error) {
    return errorResponse(error);
  }
}

/** Plain-text diagnostic — open in the browser while logged in as SUPER_ADMIN. */
export async function GET() {
  try {
    await requireRole(["SUPER_ADMIN"]);
    const ctx = await buildContext();

    const sources = await prisma.newsSource.findMany({
      select: {
        name: true,
        listingUrl: true,
        categoryId: true,
        isActive: true,
        totalScraped: true,
      },
      orderBy: { totalScraped: "desc" },
    });

    const grouped = await prisma.article.groupBy({
      by: ["categoryId"],
      where: SCRAPER_WHERE,
      _count: { _all: true },
    });

    const samples = await prisma.article.findMany({
      where: SCRAPER_WHERE,
      select: {
        slug: true,
        content: true,
        categoryId: true,
        featuredImage: true,
        sources: { select: { url: true }, take: 1 },
      },
      orderBy: { createdAt: "desc" },
      take: 6,
    });

    const lines: string[] = [];
    lines.push("=== DIAGNOSA SUMBER FOTO ===");
    lines.push(
      `Total artikel hasil scraper: ${grouped.reduce((n, g) => n + g._count._all, 0)}`,
    );
    lines.push("");
    lines.push("SUMBER BERITA (News Sources):");
    for (const s of sources) {
      lines.push(
        `- "${s.name}" | ${s.listingUrl} | brand: ${sourceLabelFromUrl(s.listingUrl) ?? "(?)"} | kategori: ${s.categoryId ? ctx.categoryName.get(s.categoryId) ?? s.categoryId : "(belum diset)"} | ${s.isActive ? "aktif" : "nonaktif"} | scraped: ${s.totalScraped}`,
      );
    }
    lines.push("");
    lines.push("ARTIKEL SCRAPER PER KATEGORI:");
    for (const g of grouped) {
      const mapped = g.categoryId ? ctx.categoryLabel.get(g.categoryId) : undefined;
      lines.push(
        `- ${g.categoryId ? ctx.categoryName.get(g.categoryId) ?? g.categoryId : "(tanpa kategori)"}: ${g._count._all} artikel → akan dikreditkan ke: ${mapped?.label ?? "TIDAK ADA SUMBER (akan dilewati)"}`,
      );
    }
    lines.push("");
    lines.push("CONTOH ARTIKEL:");
    samples.forEach((a, i) => {
      const m = a.content.match(/(Foto|Sumber):\s*[^<\n]{0,40}/i);
      lines.push(
        `${i + 1}. ${a.slug} | kategori: ${a.categoryId ? ctx.categoryName.get(a.categoryId) ?? a.categoryId : "(none)"} | sourceUrl: ${a.sources[0]?.url ?? "—"} | footer: ${footerSourceHref(a.content) ?? "—"} | kreditDiKonten: "${m ? m[0].trim() : "(tidak ditemukan)"}"`,
      );
    });

    return new Response(lines.join("\n"), {
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  } catch (error) {
    return errorResponse(error);
  }
}
